// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: octant/v1alpha/argocd_service.proto

package octantv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ArgoCDServiceName is the fully-qualified name of the ArgoCDService service.
	ArgoCDServiceName = "octant.v1alpha.ArgoCDService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ArgoCDServiceTestConnectionProcedure is the fully-qualified name of the ArgoCDService's
	// TestConnection RPC.
	ArgoCDServiceTestConnectionProcedure = "/octant.v1alpha.ArgoCDService/TestConnection"
	// ArgoCDServiceSaveArgoConnectionProcedure is the fully-qualified name of the ArgoCDService's
	// SaveArgoConnection RPC.
	ArgoCDServiceSaveArgoConnectionProcedure = "/octant.v1alpha.ArgoCDService/SaveArgoConnection"
	// ArgoCDServiceGetArgoIntegrationsProcedure is the fully-qualified name of the ArgoCDService's
	// GetArgoIntegrations RPC.
	ArgoCDServiceGetArgoIntegrationsProcedure = "/octant.v1alpha.ArgoCDService/GetArgoIntegrations"
	// ArgoCDServiceGetArgoIntegrationByNameProcedure is the fully-qualified name of the ArgoCDService's
	// GetArgoIntegrationByName RPC.
	ArgoCDServiceGetArgoIntegrationByNameProcedure = "/octant.v1alpha.ArgoCDService/GetArgoIntegrationByName"
)

// ArgoCDServiceClient is a client for the octant.v1alpha.ArgoCDService service.
type ArgoCDServiceClient interface {
	// TestConnection uses the provided request data to test the argo connection.
	TestConnection(context.Context, *connect.Request[v1alpha.TestConnectionRequest]) (*connect.Response[v1alpha.TestConnectionResponse], error)
	// SaveArgoConnection saves the argo connection details.
	SaveArgoConnection(context.Context, *connect.Request[v1alpha.SaveArgoConnectionRequest]) (*connect.Response[emptypb.Empty], error)
	// GetIntegrations returns list of argo integration names.
	GetArgoIntegrations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetArgoIntegrationsResponse], error)
	// GetIntegrations returns list of argo integration names.
	GetArgoIntegrationByName(context.Context, *connect.Request[v1alpha.GetArgoIntegrationByNameRequest]) (*connect.Response[v1alpha.GetArgoIntegrationByNameResponse], error)
}

// NewArgoCDServiceClient constructs a client for the octant.v1alpha.ArgoCDService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewArgoCDServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ArgoCDServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	argoCDServiceMethods := v1alpha.File_octant_v1alpha_argocd_service_proto.Services().ByName("ArgoCDService").Methods()
	return &argoCDServiceClient{
		testConnection: connect.NewClient[v1alpha.TestConnectionRequest, v1alpha.TestConnectionResponse](
			httpClient,
			baseURL+ArgoCDServiceTestConnectionProcedure,
			connect.WithSchema(argoCDServiceMethods.ByName("TestConnection")),
			connect.WithClientOptions(opts...),
		),
		saveArgoConnection: connect.NewClient[v1alpha.SaveArgoConnectionRequest, emptypb.Empty](
			httpClient,
			baseURL+ArgoCDServiceSaveArgoConnectionProcedure,
			connect.WithSchema(argoCDServiceMethods.ByName("SaveArgoConnection")),
			connect.WithClientOptions(opts...),
		),
		getArgoIntegrations: connect.NewClient[emptypb.Empty, v1alpha.GetArgoIntegrationsResponse](
			httpClient,
			baseURL+ArgoCDServiceGetArgoIntegrationsProcedure,
			connect.WithSchema(argoCDServiceMethods.ByName("GetArgoIntegrations")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
		getArgoIntegrationByName: connect.NewClient[v1alpha.GetArgoIntegrationByNameRequest, v1alpha.GetArgoIntegrationByNameResponse](
			httpClient,
			baseURL+ArgoCDServiceGetArgoIntegrationByNameProcedure,
			connect.WithSchema(argoCDServiceMethods.ByName("GetArgoIntegrationByName")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// argoCDServiceClient implements ArgoCDServiceClient.
type argoCDServiceClient struct {
	testConnection           *connect.Client[v1alpha.TestConnectionRequest, v1alpha.TestConnectionResponse]
	saveArgoConnection       *connect.Client[v1alpha.SaveArgoConnectionRequest, emptypb.Empty]
	getArgoIntegrations      *connect.Client[emptypb.Empty, v1alpha.GetArgoIntegrationsResponse]
	getArgoIntegrationByName *connect.Client[v1alpha.GetArgoIntegrationByNameRequest, v1alpha.GetArgoIntegrationByNameResponse]
}

// TestConnection calls octant.v1alpha.ArgoCDService.TestConnection.
func (c *argoCDServiceClient) TestConnection(ctx context.Context, req *connect.Request[v1alpha.TestConnectionRequest]) (*connect.Response[v1alpha.TestConnectionResponse], error) {
	return c.testConnection.CallUnary(ctx, req)
}

// SaveArgoConnection calls octant.v1alpha.ArgoCDService.SaveArgoConnection.
func (c *argoCDServiceClient) SaveArgoConnection(ctx context.Context, req *connect.Request[v1alpha.SaveArgoConnectionRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.saveArgoConnection.CallUnary(ctx, req)
}

// GetArgoIntegrations calls octant.v1alpha.ArgoCDService.GetArgoIntegrations.
func (c *argoCDServiceClient) GetArgoIntegrations(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetArgoIntegrationsResponse], error) {
	return c.getArgoIntegrations.CallUnary(ctx, req)
}

// GetArgoIntegrationByName calls octant.v1alpha.ArgoCDService.GetArgoIntegrationByName.
func (c *argoCDServiceClient) GetArgoIntegrationByName(ctx context.Context, req *connect.Request[v1alpha.GetArgoIntegrationByNameRequest]) (*connect.Response[v1alpha.GetArgoIntegrationByNameResponse], error) {
	return c.getArgoIntegrationByName.CallUnary(ctx, req)
}

// ArgoCDServiceHandler is an implementation of the octant.v1alpha.ArgoCDService service.
type ArgoCDServiceHandler interface {
	// TestConnection uses the provided request data to test the argo connection.
	TestConnection(context.Context, *connect.Request[v1alpha.TestConnectionRequest]) (*connect.Response[v1alpha.TestConnectionResponse], error)
	// SaveArgoConnection saves the argo connection details.
	SaveArgoConnection(context.Context, *connect.Request[v1alpha.SaveArgoConnectionRequest]) (*connect.Response[emptypb.Empty], error)
	// GetIntegrations returns list of argo integration names.
	GetArgoIntegrations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetArgoIntegrationsResponse], error)
	// GetIntegrations returns list of argo integration names.
	GetArgoIntegrationByName(context.Context, *connect.Request[v1alpha.GetArgoIntegrationByNameRequest]) (*connect.Response[v1alpha.GetArgoIntegrationByNameResponse], error)
}

// NewArgoCDServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewArgoCDServiceHandler(svc ArgoCDServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	argoCDServiceMethods := v1alpha.File_octant_v1alpha_argocd_service_proto.Services().ByName("ArgoCDService").Methods()
	argoCDServiceTestConnectionHandler := connect.NewUnaryHandler(
		ArgoCDServiceTestConnectionProcedure,
		svc.TestConnection,
		connect.WithSchema(argoCDServiceMethods.ByName("TestConnection")),
		connect.WithHandlerOptions(opts...),
	)
	argoCDServiceSaveArgoConnectionHandler := connect.NewUnaryHandler(
		ArgoCDServiceSaveArgoConnectionProcedure,
		svc.SaveArgoConnection,
		connect.WithSchema(argoCDServiceMethods.ByName("SaveArgoConnection")),
		connect.WithHandlerOptions(opts...),
	)
	argoCDServiceGetArgoIntegrationsHandler := connect.NewUnaryHandler(
		ArgoCDServiceGetArgoIntegrationsProcedure,
		svc.GetArgoIntegrations,
		connect.WithSchema(argoCDServiceMethods.ByName("GetArgoIntegrations")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	argoCDServiceGetArgoIntegrationByNameHandler := connect.NewUnaryHandler(
		ArgoCDServiceGetArgoIntegrationByNameProcedure,
		svc.GetArgoIntegrationByName,
		connect.WithSchema(argoCDServiceMethods.ByName("GetArgoIntegrationByName")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/octant.v1alpha.ArgoCDService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ArgoCDServiceTestConnectionProcedure:
			argoCDServiceTestConnectionHandler.ServeHTTP(w, r)
		case ArgoCDServiceSaveArgoConnectionProcedure:
			argoCDServiceSaveArgoConnectionHandler.ServeHTTP(w, r)
		case ArgoCDServiceGetArgoIntegrationsProcedure:
			argoCDServiceGetArgoIntegrationsHandler.ServeHTTP(w, r)
		case ArgoCDServiceGetArgoIntegrationByNameProcedure:
			argoCDServiceGetArgoIntegrationByNameHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedArgoCDServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedArgoCDServiceHandler struct{}

func (UnimplementedArgoCDServiceHandler) TestConnection(context.Context, *connect.Request[v1alpha.TestConnectionRequest]) (*connect.Response[v1alpha.TestConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ArgoCDService.TestConnection is not implemented"))
}

func (UnimplementedArgoCDServiceHandler) SaveArgoConnection(context.Context, *connect.Request[v1alpha.SaveArgoConnectionRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ArgoCDService.SaveArgoConnection is not implemented"))
}

func (UnimplementedArgoCDServiceHandler) GetArgoIntegrations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetArgoIntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ArgoCDService.GetArgoIntegrations is not implemented"))
}

func (UnimplementedArgoCDServiceHandler) GetArgoIntegrationByName(context.Context, *connect.Request[v1alpha.GetArgoIntegrationByNameRequest]) (*connect.Response[v1alpha.GetArgoIntegrationByNameResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ArgoCDService.GetArgoIntegrationByName is not implemented"))
}
