// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: octant/v1alpha/connection_service.proto

package octantv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// ConnectionServiceName is the fully-qualified name of the ConnectionService service.
	ConnectionServiceName = "octant.v1alpha.ConnectionService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// ConnectionServiceGetConnectionsProcedure is the fully-qualified name of the ConnectionService's
	// GetConnections RPC.
	ConnectionServiceGetConnectionsProcedure = "/octant.v1alpha.ConnectionService/GetConnections"
	// ConnectionServiceGetConnectionProcedure is the fully-qualified name of the ConnectionService's
	// GetConnection RPC.
	ConnectionServiceGetConnectionProcedure = "/octant.v1alpha.ConnectionService/GetConnection"
	// ConnectionServicePutConnectionProcedure is the fully-qualified name of the ConnectionService's
	// PutConnection RPC.
	ConnectionServicePutConnectionProcedure = "/octant.v1alpha.ConnectionService/PutConnection"
	// ConnectionServiceGetConnectionValidatorRunsProcedure is the fully-qualified name of the
	// ConnectionService's GetConnectionValidatorRuns RPC.
	ConnectionServiceGetConnectionValidatorRunsProcedure = "/octant.v1alpha.ConnectionService/GetConnectionValidatorRuns"
	// ConnectionServicePutConnectionValidatorRunProcedure is the fully-qualified name of the
	// ConnectionService's PutConnectionValidatorRun RPC.
	ConnectionServicePutConnectionValidatorRunProcedure = "/octant.v1alpha.ConnectionService/PutConnectionValidatorRun"
	// ConnectionServiceGetConnectionStatusProcedure is the fully-qualified name of the
	// ConnectionService's GetConnectionStatus RPC.
	ConnectionServiceGetConnectionStatusProcedure = "/octant.v1alpha.ConnectionService/GetConnectionStatus"
	// ConnectionServiceGenerateManifestsProcedure is the fully-qualified name of the
	// ConnectionService's GenerateManifests RPC.
	ConnectionServiceGenerateManifestsProcedure = "/octant.v1alpha.ConnectionService/GenerateManifests"
)

// ConnectionServiceClient is a client for the octant.v1alpha.ConnectionService service.
type ConnectionServiceClient interface {
	GetConnections(context.Context, *connect.Request[v1alpha.GetConnectionsRequest]) (*connect.Response[v1alpha.GetConnectionsResponse], error)
	GetConnection(context.Context, *connect.Request[v1alpha.GetConnectionRequest]) (*connect.Response[v1alpha.GetConnectionResponse], error)
	PutConnection(context.Context, *connect.Request[v1alpha.PutConnectionRequest]) (*connect.Response[v1alpha.PutConnectionResponse], error)
	// GetConnectionValidatorRuns gets the validator runs that exist in the validation dataset
	GetConnectionValidatorRuns(context.Context, *connect.Request[v1alpha.GetConnectionValidatorRunsRequest]) (*connect.Response[v1alpha.GetConnectionValidatorRunsResponse], error)
	// PutConnectionValidatorRun creates a new validator run for the given connection. Will create a new validator run if one already exists.
	PutConnectionValidatorRun(context.Context, *connect.Request[v1alpha.PutConnectionValidatorRunRequest]) (*connect.Response[v1alpha.PutConnectionValidatorRunResponse], error)
	// GetConnectionStatus gets the status of a connection based on dataflow and validation metrics
	GetConnectionStatus(context.Context, *connect.Request[v1alpha.GetConnectionStatusRequest]) (*connect.Response[v1alpha.GetConnectionStatusResponse], error)
	// GenerateManifests generates the manifest base on the given input and this will returns
	// the compressed zip file containing the manifests as a stream of raw bytes.
	// Note: To create a download link in the FE, the stream of file content data should be stored
	// in a typed blob and then https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static
	// should be used.
	GenerateManifests(context.Context, *connect.Request[v1alpha.GenerateManifestsRequest]) (*connect.ServerStreamForClient[v1alpha.GenerateManifestsResponse], error)
}

// NewConnectionServiceClient constructs a client for the octant.v1alpha.ConnectionService service.
// By default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped
// responses, and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewConnectionServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) ConnectionServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	connectionServiceMethods := v1alpha.File_octant_v1alpha_connection_service_proto.Services().ByName("ConnectionService").Methods()
	return &connectionServiceClient{
		getConnections: connect.NewClient[v1alpha.GetConnectionsRequest, v1alpha.GetConnectionsResponse](
			httpClient,
			baseURL+ConnectionServiceGetConnectionsProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("GetConnections")),
			connect.WithClientOptions(opts...),
		),
		getConnection: connect.NewClient[v1alpha.GetConnectionRequest, v1alpha.GetConnectionResponse](
			httpClient,
			baseURL+ConnectionServiceGetConnectionProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("GetConnection")),
			connect.WithClientOptions(opts...),
		),
		putConnection: connect.NewClient[v1alpha.PutConnectionRequest, v1alpha.PutConnectionResponse](
			httpClient,
			baseURL+ConnectionServicePutConnectionProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("PutConnection")),
			connect.WithClientOptions(opts...),
		),
		getConnectionValidatorRuns: connect.NewClient[v1alpha.GetConnectionValidatorRunsRequest, v1alpha.GetConnectionValidatorRunsResponse](
			httpClient,
			baseURL+ConnectionServiceGetConnectionValidatorRunsProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("GetConnectionValidatorRuns")),
			connect.WithClientOptions(opts...),
		),
		putConnectionValidatorRun: connect.NewClient[v1alpha.PutConnectionValidatorRunRequest, v1alpha.PutConnectionValidatorRunResponse](
			httpClient,
			baseURL+ConnectionServicePutConnectionValidatorRunProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("PutConnectionValidatorRun")),
			connect.WithClientOptions(opts...),
		),
		getConnectionStatus: connect.NewClient[v1alpha.GetConnectionStatusRequest, v1alpha.GetConnectionStatusResponse](
			httpClient,
			baseURL+ConnectionServiceGetConnectionStatusProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("GetConnectionStatus")),
			connect.WithClientOptions(opts...),
		),
		generateManifests: connect.NewClient[v1alpha.GenerateManifestsRequest, v1alpha.GenerateManifestsResponse](
			httpClient,
			baseURL+ConnectionServiceGenerateManifestsProcedure,
			connect.WithSchema(connectionServiceMethods.ByName("GenerateManifests")),
			connect.WithClientOptions(opts...),
		),
	}
}

// connectionServiceClient implements ConnectionServiceClient.
type connectionServiceClient struct {
	getConnections             *connect.Client[v1alpha.GetConnectionsRequest, v1alpha.GetConnectionsResponse]
	getConnection              *connect.Client[v1alpha.GetConnectionRequest, v1alpha.GetConnectionResponse]
	putConnection              *connect.Client[v1alpha.PutConnectionRequest, v1alpha.PutConnectionResponse]
	getConnectionValidatorRuns *connect.Client[v1alpha.GetConnectionValidatorRunsRequest, v1alpha.GetConnectionValidatorRunsResponse]
	putConnectionValidatorRun  *connect.Client[v1alpha.PutConnectionValidatorRunRequest, v1alpha.PutConnectionValidatorRunResponse]
	getConnectionStatus        *connect.Client[v1alpha.GetConnectionStatusRequest, v1alpha.GetConnectionStatusResponse]
	generateManifests          *connect.Client[v1alpha.GenerateManifestsRequest, v1alpha.GenerateManifestsResponse]
}

// GetConnections calls octant.v1alpha.ConnectionService.GetConnections.
func (c *connectionServiceClient) GetConnections(ctx context.Context, req *connect.Request[v1alpha.GetConnectionsRequest]) (*connect.Response[v1alpha.GetConnectionsResponse], error) {
	return c.getConnections.CallUnary(ctx, req)
}

// GetConnection calls octant.v1alpha.ConnectionService.GetConnection.
func (c *connectionServiceClient) GetConnection(ctx context.Context, req *connect.Request[v1alpha.GetConnectionRequest]) (*connect.Response[v1alpha.GetConnectionResponse], error) {
	return c.getConnection.CallUnary(ctx, req)
}

// PutConnection calls octant.v1alpha.ConnectionService.PutConnection.
func (c *connectionServiceClient) PutConnection(ctx context.Context, req *connect.Request[v1alpha.PutConnectionRequest]) (*connect.Response[v1alpha.PutConnectionResponse], error) {
	return c.putConnection.CallUnary(ctx, req)
}

// GetConnectionValidatorRuns calls octant.v1alpha.ConnectionService.GetConnectionValidatorRuns.
func (c *connectionServiceClient) GetConnectionValidatorRuns(ctx context.Context, req *connect.Request[v1alpha.GetConnectionValidatorRunsRequest]) (*connect.Response[v1alpha.GetConnectionValidatorRunsResponse], error) {
	return c.getConnectionValidatorRuns.CallUnary(ctx, req)
}

// PutConnectionValidatorRun calls octant.v1alpha.ConnectionService.PutConnectionValidatorRun.
func (c *connectionServiceClient) PutConnectionValidatorRun(ctx context.Context, req *connect.Request[v1alpha.PutConnectionValidatorRunRequest]) (*connect.Response[v1alpha.PutConnectionValidatorRunResponse], error) {
	return c.putConnectionValidatorRun.CallUnary(ctx, req)
}

// GetConnectionStatus calls octant.v1alpha.ConnectionService.GetConnectionStatus.
func (c *connectionServiceClient) GetConnectionStatus(ctx context.Context, req *connect.Request[v1alpha.GetConnectionStatusRequest]) (*connect.Response[v1alpha.GetConnectionStatusResponse], error) {
	return c.getConnectionStatus.CallUnary(ctx, req)
}

// GenerateManifests calls octant.v1alpha.ConnectionService.GenerateManifests.
func (c *connectionServiceClient) GenerateManifests(ctx context.Context, req *connect.Request[v1alpha.GenerateManifestsRequest]) (*connect.ServerStreamForClient[v1alpha.GenerateManifestsResponse], error) {
	return c.generateManifests.CallServerStream(ctx, req)
}

// ConnectionServiceHandler is an implementation of the octant.v1alpha.ConnectionService service.
type ConnectionServiceHandler interface {
	GetConnections(context.Context, *connect.Request[v1alpha.GetConnectionsRequest]) (*connect.Response[v1alpha.GetConnectionsResponse], error)
	GetConnection(context.Context, *connect.Request[v1alpha.GetConnectionRequest]) (*connect.Response[v1alpha.GetConnectionResponse], error)
	PutConnection(context.Context, *connect.Request[v1alpha.PutConnectionRequest]) (*connect.Response[v1alpha.PutConnectionResponse], error)
	// GetConnectionValidatorRuns gets the validator runs that exist in the validation dataset
	GetConnectionValidatorRuns(context.Context, *connect.Request[v1alpha.GetConnectionValidatorRunsRequest]) (*connect.Response[v1alpha.GetConnectionValidatorRunsResponse], error)
	// PutConnectionValidatorRun creates a new validator run for the given connection. Will create a new validator run if one already exists.
	PutConnectionValidatorRun(context.Context, *connect.Request[v1alpha.PutConnectionValidatorRunRequest]) (*connect.Response[v1alpha.PutConnectionValidatorRunResponse], error)
	// GetConnectionStatus gets the status of a connection based on dataflow and validation metrics
	GetConnectionStatus(context.Context, *connect.Request[v1alpha.GetConnectionStatusRequest]) (*connect.Response[v1alpha.GetConnectionStatusResponse], error)
	// GenerateManifests generates the manifest base on the given input and this will returns
	// the compressed zip file containing the manifests as a stream of raw bytes.
	// Note: To create a download link in the FE, the stream of file content data should be stored
	// in a typed blob and then https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static
	// should be used.
	GenerateManifests(context.Context, *connect.Request[v1alpha.GenerateManifestsRequest], *connect.ServerStream[v1alpha.GenerateManifestsResponse]) error
}

// NewConnectionServiceHandler builds an HTTP handler from the service implementation. It returns
// the path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewConnectionServiceHandler(svc ConnectionServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	connectionServiceMethods := v1alpha.File_octant_v1alpha_connection_service_proto.Services().ByName("ConnectionService").Methods()
	connectionServiceGetConnectionsHandler := connect.NewUnaryHandler(
		ConnectionServiceGetConnectionsProcedure,
		svc.GetConnections,
		connect.WithSchema(connectionServiceMethods.ByName("GetConnections")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceGetConnectionHandler := connect.NewUnaryHandler(
		ConnectionServiceGetConnectionProcedure,
		svc.GetConnection,
		connect.WithSchema(connectionServiceMethods.ByName("GetConnection")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServicePutConnectionHandler := connect.NewUnaryHandler(
		ConnectionServicePutConnectionProcedure,
		svc.PutConnection,
		connect.WithSchema(connectionServiceMethods.ByName("PutConnection")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceGetConnectionValidatorRunsHandler := connect.NewUnaryHandler(
		ConnectionServiceGetConnectionValidatorRunsProcedure,
		svc.GetConnectionValidatorRuns,
		connect.WithSchema(connectionServiceMethods.ByName("GetConnectionValidatorRuns")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServicePutConnectionValidatorRunHandler := connect.NewUnaryHandler(
		ConnectionServicePutConnectionValidatorRunProcedure,
		svc.PutConnectionValidatorRun,
		connect.WithSchema(connectionServiceMethods.ByName("PutConnectionValidatorRun")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceGetConnectionStatusHandler := connect.NewUnaryHandler(
		ConnectionServiceGetConnectionStatusProcedure,
		svc.GetConnectionStatus,
		connect.WithSchema(connectionServiceMethods.ByName("GetConnectionStatus")),
		connect.WithHandlerOptions(opts...),
	)
	connectionServiceGenerateManifestsHandler := connect.NewServerStreamHandler(
		ConnectionServiceGenerateManifestsProcedure,
		svc.GenerateManifests,
		connect.WithSchema(connectionServiceMethods.ByName("GenerateManifests")),
		connect.WithHandlerOptions(opts...),
	)
	return "/octant.v1alpha.ConnectionService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case ConnectionServiceGetConnectionsProcedure:
			connectionServiceGetConnectionsHandler.ServeHTTP(w, r)
		case ConnectionServiceGetConnectionProcedure:
			connectionServiceGetConnectionHandler.ServeHTTP(w, r)
		case ConnectionServicePutConnectionProcedure:
			connectionServicePutConnectionHandler.ServeHTTP(w, r)
		case ConnectionServiceGetConnectionValidatorRunsProcedure:
			connectionServiceGetConnectionValidatorRunsHandler.ServeHTTP(w, r)
		case ConnectionServicePutConnectionValidatorRunProcedure:
			connectionServicePutConnectionValidatorRunHandler.ServeHTTP(w, r)
		case ConnectionServiceGetConnectionStatusProcedure:
			connectionServiceGetConnectionStatusHandler.ServeHTTP(w, r)
		case ConnectionServiceGenerateManifestsProcedure:
			connectionServiceGenerateManifestsHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedConnectionServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedConnectionServiceHandler struct{}

func (UnimplementedConnectionServiceHandler) GetConnections(context.Context, *connect.Request[v1alpha.GetConnectionsRequest]) (*connect.Response[v1alpha.GetConnectionsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.GetConnections is not implemented"))
}

func (UnimplementedConnectionServiceHandler) GetConnection(context.Context, *connect.Request[v1alpha.GetConnectionRequest]) (*connect.Response[v1alpha.GetConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.GetConnection is not implemented"))
}

func (UnimplementedConnectionServiceHandler) PutConnection(context.Context, *connect.Request[v1alpha.PutConnectionRequest]) (*connect.Response[v1alpha.PutConnectionResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.PutConnection is not implemented"))
}

func (UnimplementedConnectionServiceHandler) GetConnectionValidatorRuns(context.Context, *connect.Request[v1alpha.GetConnectionValidatorRunsRequest]) (*connect.Response[v1alpha.GetConnectionValidatorRunsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.GetConnectionValidatorRuns is not implemented"))
}

func (UnimplementedConnectionServiceHandler) PutConnectionValidatorRun(context.Context, *connect.Request[v1alpha.PutConnectionValidatorRunRequest]) (*connect.Response[v1alpha.PutConnectionValidatorRunResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.PutConnectionValidatorRun is not implemented"))
}

func (UnimplementedConnectionServiceHandler) GetConnectionStatus(context.Context, *connect.Request[v1alpha.GetConnectionStatusRequest]) (*connect.Response[v1alpha.GetConnectionStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.GetConnectionStatus is not implemented"))
}

func (UnimplementedConnectionServiceHandler) GenerateManifests(context.Context, *connect.Request[v1alpha.GenerateManifestsRequest], *connect.ServerStream[v1alpha.GenerateManifestsResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.ConnectionService.GenerateManifests is not implemented"))
}
