// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: octant/v1alpha/datadog_service.proto

package octantv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// DatadogServiceName is the fully-qualified name of the DatadogService service.
	DatadogServiceName = "octant.v1alpha.DatadogService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// DatadogServiceGetIntegrationsProcedure is the fully-qualified name of the DatadogService's
	// GetIntegrations RPC.
	DatadogServiceGetIntegrationsProcedure = "/octant.v1alpha.DatadogService/GetIntegrations"
	// DatadogServiceSaveIntegrationProcedure is the fully-qualified name of the DatadogService's
	// SaveIntegration RPC.
	DatadogServiceSaveIntegrationProcedure = "/octant.v1alpha.DatadogService/SaveIntegration"
)

// DatadogServiceClient is a client for the octant.v1alpha.DatadogService service.
type DatadogServiceClient interface {
	// GetIntegrations returns list of datadog integration names.
	GetIntegrations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetIntegrationsResponse], error)
	// SaveIntegration saves the given datadog integration.
	// If the integration already exists, this will override the saved data with the one provided.
	SaveIntegration(context.Context, *connect.Request[v1alpha.SaveIntegrationRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewDatadogServiceClient constructs a client for the octant.v1alpha.DatadogService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewDatadogServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) DatadogServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	datadogServiceMethods := v1alpha.File_octant_v1alpha_datadog_service_proto.Services().ByName("DatadogService").Methods()
	return &datadogServiceClient{
		getIntegrations: connect.NewClient[emptypb.Empty, v1alpha.GetIntegrationsResponse](
			httpClient,
			baseURL+DatadogServiceGetIntegrationsProcedure,
			connect.WithSchema(datadogServiceMethods.ByName("GetIntegrations")),
			connect.WithClientOptions(opts...),
		),
		saveIntegration: connect.NewClient[v1alpha.SaveIntegrationRequest, emptypb.Empty](
			httpClient,
			baseURL+DatadogServiceSaveIntegrationProcedure,
			connect.WithSchema(datadogServiceMethods.ByName("SaveIntegration")),
			connect.WithClientOptions(opts...),
		),
	}
}

// datadogServiceClient implements DatadogServiceClient.
type datadogServiceClient struct {
	getIntegrations *connect.Client[emptypb.Empty, v1alpha.GetIntegrationsResponse]
	saveIntegration *connect.Client[v1alpha.SaveIntegrationRequest, emptypb.Empty]
}

// GetIntegrations calls octant.v1alpha.DatadogService.GetIntegrations.
func (c *datadogServiceClient) GetIntegrations(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetIntegrationsResponse], error) {
	return c.getIntegrations.CallUnary(ctx, req)
}

// SaveIntegration calls octant.v1alpha.DatadogService.SaveIntegration.
func (c *datadogServiceClient) SaveIntegration(ctx context.Context, req *connect.Request[v1alpha.SaveIntegrationRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.saveIntegration.CallUnary(ctx, req)
}

// DatadogServiceHandler is an implementation of the octant.v1alpha.DatadogService service.
type DatadogServiceHandler interface {
	// GetIntegrations returns list of datadog integration names.
	GetIntegrations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetIntegrationsResponse], error)
	// SaveIntegration saves the given datadog integration.
	// If the integration already exists, this will override the saved data with the one provided.
	SaveIntegration(context.Context, *connect.Request[v1alpha.SaveIntegrationRequest]) (*connect.Response[emptypb.Empty], error)
}

// NewDatadogServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewDatadogServiceHandler(svc DatadogServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	datadogServiceMethods := v1alpha.File_octant_v1alpha_datadog_service_proto.Services().ByName("DatadogService").Methods()
	datadogServiceGetIntegrationsHandler := connect.NewUnaryHandler(
		DatadogServiceGetIntegrationsProcedure,
		svc.GetIntegrations,
		connect.WithSchema(datadogServiceMethods.ByName("GetIntegrations")),
		connect.WithHandlerOptions(opts...),
	)
	datadogServiceSaveIntegrationHandler := connect.NewUnaryHandler(
		DatadogServiceSaveIntegrationProcedure,
		svc.SaveIntegration,
		connect.WithSchema(datadogServiceMethods.ByName("SaveIntegration")),
		connect.WithHandlerOptions(opts...),
	)
	return "/octant.v1alpha.DatadogService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case DatadogServiceGetIntegrationsProcedure:
			datadogServiceGetIntegrationsHandler.ServeHTTP(w, r)
		case DatadogServiceSaveIntegrationProcedure:
			datadogServiceSaveIntegrationHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedDatadogServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedDatadogServiceHandler struct{}

func (UnimplementedDatadogServiceHandler) GetIntegrations(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.GetIntegrationsResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.DatadogService.GetIntegrations is not implemented"))
}

func (UnimplementedDatadogServiceHandler) SaveIntegration(context.Context, *connect.Request[v1alpha.SaveIntegrationRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.DatadogService.SaveIntegration is not implemented"))
}
