// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: octant/v1alpha/install_service.proto

package octantv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// InstallServiceName is the fully-qualified name of the InstallService service.
	InstallServiceName = "octant.v1alpha.InstallService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// InstallServiceInstallMDAIHubProcedure is the fully-qualified name of the InstallService's
	// InstallMDAIHub RPC.
	InstallServiceInstallMDAIHubProcedure = "/octant.v1alpha.InstallService/InstallMDAIHub"
	// InstallServiceGetInstallStatusProcedure is the fully-qualified name of the InstallService's
	// GetInstallStatus RPC.
	InstallServiceGetInstallStatusProcedure = "/octant.v1alpha.InstallService/GetInstallStatus"
)

// InstallServiceClient is a client for the octant.v1alpha.InstallService service.
type InstallServiceClient interface {
	// InstallMDAIHub initiates installing the mdai smart hub with the provided request data.
	InstallMDAIHub(context.Context, *connect.Request[v1alpha.InstallMDAIHubRequest]) (*connect.Response[emptypb.Empty], error)
	// GetInstallStatus creates a response stream with mdai install status updates.
	GetInstallStatus(context.Context, *connect.Request[v1alpha.GetInstallStatusRequest]) (*connect.ServerStreamForClient[v1alpha.GetInstallStatusResponse], error)
}

// NewInstallServiceClient constructs a client for the octant.v1alpha.InstallService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewInstallServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) InstallServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	installServiceMethods := v1alpha.File_octant_v1alpha_install_service_proto.Services().ByName("InstallService").Methods()
	return &installServiceClient{
		installMDAIHub: connect.NewClient[v1alpha.InstallMDAIHubRequest, emptypb.Empty](
			httpClient,
			baseURL+InstallServiceInstallMDAIHubProcedure,
			connect.WithSchema(installServiceMethods.ByName("InstallMDAIHub")),
			connect.WithClientOptions(opts...),
		),
		getInstallStatus: connect.NewClient[v1alpha.GetInstallStatusRequest, v1alpha.GetInstallStatusResponse](
			httpClient,
			baseURL+InstallServiceGetInstallStatusProcedure,
			connect.WithSchema(installServiceMethods.ByName("GetInstallStatus")),
			connect.WithIdempotency(connect.IdempotencyNoSideEffects),
			connect.WithClientOptions(opts...),
		),
	}
}

// installServiceClient implements InstallServiceClient.
type installServiceClient struct {
	installMDAIHub   *connect.Client[v1alpha.InstallMDAIHubRequest, emptypb.Empty]
	getInstallStatus *connect.Client[v1alpha.GetInstallStatusRequest, v1alpha.GetInstallStatusResponse]
}

// InstallMDAIHub calls octant.v1alpha.InstallService.InstallMDAIHub.
func (c *installServiceClient) InstallMDAIHub(ctx context.Context, req *connect.Request[v1alpha.InstallMDAIHubRequest]) (*connect.Response[emptypb.Empty], error) {
	return c.installMDAIHub.CallUnary(ctx, req)
}

// GetInstallStatus calls octant.v1alpha.InstallService.GetInstallStatus.
func (c *installServiceClient) GetInstallStatus(ctx context.Context, req *connect.Request[v1alpha.GetInstallStatusRequest]) (*connect.ServerStreamForClient[v1alpha.GetInstallStatusResponse], error) {
	return c.getInstallStatus.CallServerStream(ctx, req)
}

// InstallServiceHandler is an implementation of the octant.v1alpha.InstallService service.
type InstallServiceHandler interface {
	// InstallMDAIHub initiates installing the mdai smart hub with the provided request data.
	InstallMDAIHub(context.Context, *connect.Request[v1alpha.InstallMDAIHubRequest]) (*connect.Response[emptypb.Empty], error)
	// GetInstallStatus creates a response stream with mdai install status updates.
	GetInstallStatus(context.Context, *connect.Request[v1alpha.GetInstallStatusRequest], *connect.ServerStream[v1alpha.GetInstallStatusResponse]) error
}

// NewInstallServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewInstallServiceHandler(svc InstallServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	installServiceMethods := v1alpha.File_octant_v1alpha_install_service_proto.Services().ByName("InstallService").Methods()
	installServiceInstallMDAIHubHandler := connect.NewUnaryHandler(
		InstallServiceInstallMDAIHubProcedure,
		svc.InstallMDAIHub,
		connect.WithSchema(installServiceMethods.ByName("InstallMDAIHub")),
		connect.WithHandlerOptions(opts...),
	)
	installServiceGetInstallStatusHandler := connect.NewServerStreamHandler(
		InstallServiceGetInstallStatusProcedure,
		svc.GetInstallStatus,
		connect.WithSchema(installServiceMethods.ByName("GetInstallStatus")),
		connect.WithIdempotency(connect.IdempotencyNoSideEffects),
		connect.WithHandlerOptions(opts...),
	)
	return "/octant.v1alpha.InstallService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case InstallServiceInstallMDAIHubProcedure:
			installServiceInstallMDAIHubHandler.ServeHTTP(w, r)
		case InstallServiceGetInstallStatusProcedure:
			installServiceGetInstallStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedInstallServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedInstallServiceHandler struct{}

func (UnimplementedInstallServiceHandler) InstallMDAIHub(context.Context, *connect.Request[v1alpha.InstallMDAIHubRequest]) (*connect.Response[emptypb.Empty], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.InstallService.InstallMDAIHub is not implemented"))
}

func (UnimplementedInstallServiceHandler) GetInstallStatus(context.Context, *connect.Request[v1alpha.GetInstallStatusRequest], *connect.ServerStream[v1alpha.GetInstallStatusResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.InstallService.GetInstallStatus is not implemented"))
}
