// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: octant/v1alpha/setting_service.proto

package octantv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// SettingServiceName is the fully-qualified name of the SettingService service.
	SettingServiceName = "octant.v1alpha.SettingService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// SettingServiceUpdateProcedure is the fully-qualified name of the SettingService's Update RPC.
	SettingServiceUpdateProcedure = "/octant.v1alpha.SettingService/Update"
)

// SettingServiceClient is a client for the octant.v1alpha.SettingService service.
type SettingServiceClient interface {
	// Update updates the relevant configmap/secret and then redeploy necessary collectors to relfect the changes.
	// If an update is in progress, this will immediately return with an error code `unavailable`.
	// Otherwise, this will continuously give update until the update is complete or errored.
	// Note: Please take a look at https://connectrpc.com/docs/protocol/#error-codes for all other possible error codes.
	Update(context.Context, *connect.Request[v1alpha.UpdateRequest]) (*connect.ServerStreamForClient[v1alpha.UpdateResponse], error)
}

// NewSettingServiceClient constructs a client for the octant.v1alpha.SettingService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewSettingServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) SettingServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	settingServiceMethods := v1alpha.File_octant_v1alpha_setting_service_proto.Services().ByName("SettingService").Methods()
	return &settingServiceClient{
		update: connect.NewClient[v1alpha.UpdateRequest, v1alpha.UpdateResponse](
			httpClient,
			baseURL+SettingServiceUpdateProcedure,
			connect.WithSchema(settingServiceMethods.ByName("Update")),
			connect.WithClientOptions(opts...),
		),
	}
}

// settingServiceClient implements SettingServiceClient.
type settingServiceClient struct {
	update *connect.Client[v1alpha.UpdateRequest, v1alpha.UpdateResponse]
}

// Update calls octant.v1alpha.SettingService.Update.
func (c *settingServiceClient) Update(ctx context.Context, req *connect.Request[v1alpha.UpdateRequest]) (*connect.ServerStreamForClient[v1alpha.UpdateResponse], error) {
	return c.update.CallServerStream(ctx, req)
}

// SettingServiceHandler is an implementation of the octant.v1alpha.SettingService service.
type SettingServiceHandler interface {
	// Update updates the relevant configmap/secret and then redeploy necessary collectors to relfect the changes.
	// If an update is in progress, this will immediately return with an error code `unavailable`.
	// Otherwise, this will continuously give update until the update is complete or errored.
	// Note: Please take a look at https://connectrpc.com/docs/protocol/#error-codes for all other possible error codes.
	Update(context.Context, *connect.Request[v1alpha.UpdateRequest], *connect.ServerStream[v1alpha.UpdateResponse]) error
}

// NewSettingServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewSettingServiceHandler(svc SettingServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	settingServiceMethods := v1alpha.File_octant_v1alpha_setting_service_proto.Services().ByName("SettingService").Methods()
	settingServiceUpdateHandler := connect.NewServerStreamHandler(
		SettingServiceUpdateProcedure,
		svc.Update,
		connect.WithSchema(settingServiceMethods.ByName("Update")),
		connect.WithHandlerOptions(opts...),
	)
	return "/octant.v1alpha.SettingService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case SettingServiceUpdateProcedure:
			settingServiceUpdateHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedSettingServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedSettingServiceHandler struct{}

func (UnimplementedSettingServiceHandler) Update(context.Context, *connect.Request[v1alpha.UpdateRequest], *connect.ServerStream[v1alpha.UpdateResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("octant.v1alpha.SettingService.Update is not implemented"))
}
