syntax = "proto3";

package budget.v1alpha;

import "budget/v1alpha/type.proto";
import "buf/validate/validate.proto";

service FilterService {
  // GetFilter returns the current filter setting of the given filter type.
  // If  an update is in progress, this will return with an error code `unavailable`.
  rpc GetFilter(GetFilterRequest) returns (GetFilterResponse) {}
  // UpdateFilter attempts to update filter setting of the given filter type.
  // If an update is in progress, this will immediately return with an error code `unavailable`.
  // Otherwise, this will continuously give update until the update is complete or errored.
  rpc UpdateFilter(UpdateFilterRequest) returns (stream UpdateFilterResponse) {}
}

message GetFilterRequest {
  // type contains the type of the filter to retrieve.
  FilterType type = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  // namespace is the kubernetes namespace to install into.
  string namespace = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 3 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message GetFilterResponse {
  Filter data = 1;
}

message UpdateFilterRequest {
  // data contains the filter setting data to update.
  // `type` indicates which filter type should be updated.
  Filter data = 1 [(buf.validate.field).required = true];
  // namespace is the kubernetes namespace to install into.
  string namespace = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 3 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message UpdateFilterResponse {
  enum Status {
    STATUS_UNSPECIFIED = 0;
    // STATUS_VALUE_UPDATED means the data have been updated in MDAI gateway.
    STATUS_VALUE_UPDATED = 1;
    // STATUS_WAIT_PROPAGATION means we are waiting for the collectors to restart with the new values.
    STATUS_WAIT_PROPAGATION = 2;
    // STATUS_COMPLETED means collectors are all updated.
    STATUS_COMPLETED = 3;
  }
  Status status = 1;
}
