syntax = "proto3";

package budget.v1alpha;

import "budget/v1alpha/type.proto";
import "buf/validate/validate.proto";

service TimeframeService {
  // TimeframeStatus returns timeframe status for each timeframe.
  rpc TimeframeStatus(TimeframeStatusRequest) returns (TimeframeStatusResponse) {}
}

message TimeframeStatusRequest {
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 1 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // namespace is the kubernetes namespace to install into.
  string namespace = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message TimeframeStatusResponse {
  // Code represents the status code of a given timeframe.
  enum Code {
    CODE_UNSPECIFIED = 0;
    // CODE_OK means user is allow to select the given timeframe.
    CODE_OK = 1;
    // CODE_NO_DATA means connection is not set, so no data to show.
    CODE_NO_DATA = 2;
    // CODE_NOT_ENOUGH means there are not enough data to show for the given timeframe.
    CODE_NOT_ENOUGH = 3;
  }

  message Status {
    // timeframe contains the timeframe.
    Timeframe timeframe = 1;
    // status contains the status code of the timeframe.
    Code status = 3;
  }

  // statuses contains status of each timeframe.
  // Note: this array will not contain duplicate timeframes.
  repeated Status statuses = 1;

  // trace will contain true if there are data for traces.
  // Otherwise, this will contain false.
  // Note: this containing true just means there are data,
  // and it doesn't necessarily mean there will be data
  // for the user's selected timeframe.
  bool trace = 2;

  // log will contain true if there are data for logs.
  // Otherwise, this will contain false.
  // Note: this containing true just means there are data,
  // and it doesn't necessarily mean there will be data
  // for the user's selected timeframe.
  bool log = 3;
}
