syntax = "proto3";

package budget.v1alpha;

import "buf/validate/validate.proto";

// Timeframe represents possible timeframes.
enum Timeframe {
  TIMEFRAME_UNSPECIFIED = 0;
  // TIMEFRAME_24HR means the last 24 hours.
  TIMEFRAME_24HR = 1;
  // TIMEFRAME_MTD means month to date.
  TIMEFRAME_MTD = 2;
  // TIMEFRAME_LM means last month.
  TIMEFRAME_LM = 3;
}

// FilterType represents the type of filters supported.
enum FilterType {
  FILTER_TYPE_UNSPECIFIED = 0;
  FILTER_TYPE_LOG = 1;
  FILTER_TYPE_TRACE = 2;
}

message Filter {
  // type contains the filter type.
  FilterType type = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  // pct_sampled contains the sampling percentage.
  uint32 pct_sampled = 2 [(buf.validate.field).uint32 = {
    gte: 0
    lt: 101
  }];
  // include_err indcates if errors should be included.
  bool include_err = 3;
}

message Overall {
  message Metric {
    // received represents the total amount of data recieved.
    // For log, the unit is in GB; For trace, the unit is in mm Events.
    double received = 1;
    // sent represents the total amount of data send.
    // For log, the unit is in GB; For trace, the unit is in mm Events.
    double sent = 2;
    // filtered represents the difference between sent and recieved.
    // For log, the unit is in GB; For trace, the unit is in mm Events.
    double filtered = 3;
    // cost_rate contains the per GB (for log) or the per mm Events (for traces) cost rate, rounding to the nearest two decimal places.
    float cost_rate = 4;
    // pct contains the percentage of total overall cost, rounding to the nearest two decimal places (e.g., 1.23%).
    float pct = 5;
    // cost contains the total cost, rounding to the nearest two decimal places.
    double cost = 6;
  }

  // cost contains the total cost for log and trace, rounding to the nearest two decimal places.
  double cost = 1;
  // log contains overall metric data for logs.
  Metric log = 3;
  // trace contains overall metric data for traces.
  Metric trace = 4;
}

message Log {
  // name is the service name.
  string name = 1;
  //sent represents the amount of data send (in GB).
  double sent = 3;
  // pct contains the percentage of total log cost, rounding to the nearest two decimal places (e.g., 1.23%).
  float pct = 4;
  // cost contains the total cost, rounding to the nearest two decimal places.
  double cost = 5;
}

message Span {
  // name is the trace root span name.
  string name = 1;
  // breath contains the span breath.
  int64 breath = 2;
  // depth contains the span depth.
  int64 depth = 3;
  // invocations contains the number of invocations.
  int64 invocations = 4;
  // cost contains the total cost, rounding to the nearest two decimal places.
  double cost = 8;
}
