// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octant/v1alpha/connection_service.proto

package octantv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateManifestsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,2,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	// format contains output format of the manifests.
	Format ManifestOutFormat `protobuf:"varint,3,opt,name=format,proto3,enum=octant.v1alpha.ManifestOutFormat" json:"format,omitempty"`
	// telemetry_types is used to generate the manifests.
	TelemetryTypes []MLTType `protobuf:"varint,4,rep,packed,name=telemetry_types,json=telemetryTypes,proto3,enum=octant.v1alpha.MLTType" json:"telemetry_types,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GenerateManifestsRequest) Reset() {
	*x = GenerateManifestsRequest{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateManifestsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateManifestsRequest) ProtoMessage() {}

func (x *GenerateManifestsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateManifestsRequest.ProtoReflect.Descriptor instead.
func (*GenerateManifestsRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateManifestsRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GenerateManifestsRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

func (x *GenerateManifestsRequest) GetFormat() ManifestOutFormat {
	if x != nil {
		return x.Format
	}
	return ManifestOutFormat_MANIFEST_OUT_FORMAT_UNSPECIFIED
}

func (x *GenerateManifestsRequest) GetTelemetryTypes() []MLTType {
	if x != nil {
		return x.TelemetryTypes
	}
	return nil
}

type GenerateManifestsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data contains a chunk of the file content as raw bytes.
	Data []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// total is the total number of bytes for current file.
	Total uint64 `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	// type is the MIME type of the file. (e.g., zip)
	Type          string `protobuf:"bytes,3,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateManifestsResponse) Reset() {
	*x = GenerateManifestsResponse{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateManifestsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateManifestsResponse) ProtoMessage() {}

func (x *GenerateManifestsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateManifestsResponse.ProtoReflect.Descriptor instead.
func (*GenerateManifestsResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateManifestsResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *GenerateManifestsResponse) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *GenerateManifestsResponse) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

type GetConnectionStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,2,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetConnectionStatusRequest) Reset() {
	*x = GetConnectionStatusRequest{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusRequest) ProtoMessage() {}

func (x *GetConnectionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusRequest.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetConnectionStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetConnectionStatusRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

type GetConnectionStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// receiving_data indicates if the Connection's Collector is receiving telemetry for its configured Telemetry types
	ReceivingData bool `protobuf:"varint,1,opt,name=receiving_data,json=receivingData,proto3" json:"receiving_data,omitempty"`
	// sending_data indicates if the Connection's Collector is sending telemetry for its configured Telemetry types
	SendingData bool `protobuf:"varint,2,opt,name=sending_data,json=sendingData,proto3" json:"sending_data,omitempty"`
	// sending_data indicates if the data coming to the Collector fulfills validator parity or policy requirements
	DataIntegrity bool `protobuf:"varint,3,opt,name=data_integrity,json=dataIntegrity,proto3" json:"data_integrity,omitempty"`
	// validation_results is a map of granular validation details per data type (MLT)
	ValidationResults *ValidationResultsBySignal `protobuf:"bytes,4,opt,name=validation_results,json=validationResults,proto3" json:"validation_results,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetConnectionStatusResponse) Reset() {
	*x = GetConnectionStatusResponse{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetConnectionStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetConnectionStatusResponse) ProtoMessage() {}

func (x *GetConnectionStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetConnectionStatusResponse.ProtoReflect.Descriptor instead.
func (*GetConnectionStatusResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{3}
}

func (x *GetConnectionStatusResponse) GetReceivingData() bool {
	if x != nil {
		return x.ReceivingData
	}
	return false
}

func (x *GetConnectionStatusResponse) GetSendingData() bool {
	if x != nil {
		return x.SendingData
	}
	return false
}

func (x *GetConnectionStatusResponse) GetDataIntegrity() bool {
	if x != nil {
		return x.DataIntegrity
	}
	return false
}

func (x *GetConnectionStatusResponse) GetValidationResults() *ValidationResultsBySignal {
	if x != nil {
		return x.ValidationResults
	}
	return nil
}

type ValidationResultsBySignal struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Logs          *ValidationResult      `protobuf:"bytes,1,opt,name=logs,proto3" json:"logs,omitempty"`
	Metrics       *ValidationResult      `protobuf:"bytes,2,opt,name=metrics,proto3" json:"metrics,omitempty"`
	Traces        *ValidationResult      `protobuf:"bytes,3,opt,name=traces,proto3" json:"traces,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResultsBySignal) Reset() {
	*x = ValidationResultsBySignal{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResultsBySignal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResultsBySignal) ProtoMessage() {}

func (x *ValidationResultsBySignal) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResultsBySignal.ProtoReflect.Descriptor instead.
func (*ValidationResultsBySignal) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{4}
}

func (x *ValidationResultsBySignal) GetLogs() *ValidationResult {
	if x != nil {
		return x.Logs
	}
	return nil
}

func (x *ValidationResultsBySignal) GetMetrics() *ValidationResult {
	if x != nil {
		return x.Metrics
	}
	return nil
}

func (x *ValidationResultsBySignal) GetTraces() *ValidationResult {
	if x != nil {
		return x.Traces
	}
	return nil
}

type ValidationResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parity indicates if the ingress telemetry payloads match the egress telemetry payloads
	Parity bool `protobuf:"varint,1,opt,name=parity,proto3" json:"parity,omitempty"`
	// parity indicates if the egress telemetry payloads fulfill the MDAI validator policy
	Policy bool `protobuf:"varint,2,opt,name=policy,proto3" json:"policy,omitempty"`
	// attributes is a map of attributes to per-attribute parity/policy checks
	Attributes    *ValidationAttributes `protobuf:"bytes,3,opt,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationResult) Reset() {
	*x = ValidationResult{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationResult) ProtoMessage() {}

func (x *ValidationResult) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationResult.ProtoReflect.Descriptor instead.
func (*ValidationResult) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{5}
}

func (x *ValidationResult) GetParity() bool {
	if x != nil {
		return x.Parity
	}
	return false
}

func (x *ValidationResult) GetPolicy() bool {
	if x != nil {
		return x.Policy
	}
	return false
}

func (x *ValidationResult) GetAttributes() *ValidationAttributes {
	if x != nil {
		return x.Attributes
	}
	return nil
}

type ValidationAttributes struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// parity indicates if the ingress attribute matches the attribute on egress
	Parity map[string]bool `protobuf:"bytes,1,rep,name=parity,proto3" json:"parity,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	// parity indicates if the attribute fulfills the MDAI validator policy for this attribute
	Policy        map[string]bool `protobuf:"bytes,2,rep,name=policy,proto3" json:"policy,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidationAttributes) Reset() {
	*x = ValidationAttributes{}
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidationAttributes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidationAttributes) ProtoMessage() {}

func (x *ValidationAttributes) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_connection_service_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidationAttributes.ProtoReflect.Descriptor instead.
func (*ValidationAttributes) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_connection_service_proto_rawDescGZIP(), []int{6}
}

func (x *ValidationAttributes) GetParity() map[string]bool {
	if x != nil {
		return x.Parity
	}
	return nil
}

func (x *ValidationAttributes) GetPolicy() map[string]bool {
	if x != nil {
		return x.Policy
	}
	return nil
}

var File_octant_v1alpha_connection_service_proto protoreflect.FileDescriptor

const file_octant_v1alpha_connection_service_proto_rawDesc = "" +
	"\n" +
	"'octant/v1alpha/connection_service.proto\x12\x0eoctant.v1alpha\x1a\x1bbuf/validate/validate.proto\x1a\x19octant/v1alpha/type.proto\"\xd8\x02\n" +
	"\x18GenerateManifestsRequest\x12I\n" +
	"\tnamespace\x18\x01 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12S\n" +
	"\x0fconnection_name\x18\x02 \x01(\tB*\xbaH'r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\x12F\n" +
	"\x06format\x18\x03 \x01(\x0e2!.octant.v1alpha.ManifestOutFormatB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x06format\x12T\n" +
	"\x0ftelemetry_types\x18\x04 \x03(\x0e2\x17.octant.v1alpha.MLTTypeB\x12\xbaH\x0f\xc8\x01\x01\x92\x01\t\x18\x01\"\x05\x82\x01\x02\x10\x01R\x0etelemetryTypes\"Y\n" +
	"\x19GenerateManifestsResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x04R\x05total\x12\x12\n" +
	"\x04type\x18\x03 \x01(\tR\x04type\"\xbc\x01\n" +
	"\x1aGetConnectionStatusRequest\x12I\n" +
	"\tnamespace\x18\x01 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12S\n" +
	"\x0fconnection_name\x18\x02 \x01(\tB*\xbaH'r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\"\xe8\x01\n" +
	"\x1bGetConnectionStatusResponse\x12%\n" +
	"\x0ereceiving_data\x18\x01 \x01(\bR\rreceivingData\x12!\n" +
	"\fsending_data\x18\x02 \x01(\bR\vsendingData\x12%\n" +
	"\x0edata_integrity\x18\x03 \x01(\bR\rdataIntegrity\x12X\n" +
	"\x12validation_results\x18\x04 \x01(\v2).octant.v1alpha.ValidationResultsBySignalR\x11validationResults\"\xc7\x01\n" +
	"\x19ValidationResultsBySignal\x124\n" +
	"\x04logs\x18\x01 \x01(\v2 .octant.v1alpha.ValidationResultR\x04logs\x12:\n" +
	"\ametrics\x18\x02 \x01(\v2 .octant.v1alpha.ValidationResultR\ametrics\x128\n" +
	"\x06traces\x18\x03 \x01(\v2 .octant.v1alpha.ValidationResultR\x06traces\"\x88\x01\n" +
	"\x10ValidationResult\x12\x16\n" +
	"\x06parity\x18\x01 \x01(\bR\x06parity\x12\x16\n" +
	"\x06policy\x18\x02 \x01(\bR\x06policy\x12D\n" +
	"\n" +
	"attributes\x18\x03 \x01(\v2$.octant.v1alpha.ValidationAttributesR\n" +
	"attributes\"\xa0\x02\n" +
	"\x14ValidationAttributes\x12H\n" +
	"\x06parity\x18\x01 \x03(\v20.octant.v1alpha.ValidationAttributes.ParityEntryR\x06parity\x12H\n" +
	"\x06policy\x18\x02 \x03(\v20.octant.v1alpha.ValidationAttributes.PolicyEntryR\x06policy\x1a9\n" +
	"\vParityEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x01\x1a9\n" +
	"\vPolicyEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\bR\x05value:\x028\x012\xf3\x01\n" +
	"\x11ConnectionService\x12p\n" +
	"\x13GetConnectionStatus\x12*.octant.v1alpha.GetConnectionStatusRequest\x1a+.octant.v1alpha.GetConnectionStatusResponse\"\x00\x12l\n" +
	"\x11GenerateManifests\x12(.octant.v1alpha.GenerateManifestsRequest\x1a).octant.v1alpha.GenerateManifestsResponse\"\x000\x01B\xd1\x01\n" +
	"\x12com.octant.v1alphaB\x16ConnectionServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha;octantv1alpha\xa2\x02\x03OXX\xaa\x02\x0eOctant.V1alpha\xca\x02\x0eOctant\\V1alpha\xe2\x02\x1aOctant\\V1alpha\\GPBMetadata\xea\x02\x0fOctant::V1alphab\x06proto3"

var (
	file_octant_v1alpha_connection_service_proto_rawDescOnce sync.Once
	file_octant_v1alpha_connection_service_proto_rawDescData []byte
)

func file_octant_v1alpha_connection_service_proto_rawDescGZIP() []byte {
	file_octant_v1alpha_connection_service_proto_rawDescOnce.Do(func() {
		file_octant_v1alpha_connection_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octant_v1alpha_connection_service_proto_rawDesc), len(file_octant_v1alpha_connection_service_proto_rawDesc)))
	})
	return file_octant_v1alpha_connection_service_proto_rawDescData
}

var file_octant_v1alpha_connection_service_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_octant_v1alpha_connection_service_proto_goTypes = []any{
	(*GenerateManifestsRequest)(nil),    // 0: octant.v1alpha.GenerateManifestsRequest
	(*GenerateManifestsResponse)(nil),   // 1: octant.v1alpha.GenerateManifestsResponse
	(*GetConnectionStatusRequest)(nil),  // 2: octant.v1alpha.GetConnectionStatusRequest
	(*GetConnectionStatusResponse)(nil), // 3: octant.v1alpha.GetConnectionStatusResponse
	(*ValidationResultsBySignal)(nil),   // 4: octant.v1alpha.ValidationResultsBySignal
	(*ValidationResult)(nil),            // 5: octant.v1alpha.ValidationResult
	(*ValidationAttributes)(nil),        // 6: octant.v1alpha.ValidationAttributes
	nil,                                 // 7: octant.v1alpha.ValidationAttributes.ParityEntry
	nil,                                 // 8: octant.v1alpha.ValidationAttributes.PolicyEntry
	(ManifestOutFormat)(0),              // 9: octant.v1alpha.ManifestOutFormat
	(MLTType)(0),                        // 10: octant.v1alpha.MLTType
}
var file_octant_v1alpha_connection_service_proto_depIdxs = []int32{
	9,  // 0: octant.v1alpha.GenerateManifestsRequest.format:type_name -> octant.v1alpha.ManifestOutFormat
	10, // 1: octant.v1alpha.GenerateManifestsRequest.telemetry_types:type_name -> octant.v1alpha.MLTType
	4,  // 2: octant.v1alpha.GetConnectionStatusResponse.validation_results:type_name -> octant.v1alpha.ValidationResultsBySignal
	5,  // 3: octant.v1alpha.ValidationResultsBySignal.logs:type_name -> octant.v1alpha.ValidationResult
	5,  // 4: octant.v1alpha.ValidationResultsBySignal.metrics:type_name -> octant.v1alpha.ValidationResult
	5,  // 5: octant.v1alpha.ValidationResultsBySignal.traces:type_name -> octant.v1alpha.ValidationResult
	6,  // 6: octant.v1alpha.ValidationResult.attributes:type_name -> octant.v1alpha.ValidationAttributes
	7,  // 7: octant.v1alpha.ValidationAttributes.parity:type_name -> octant.v1alpha.ValidationAttributes.ParityEntry
	8,  // 8: octant.v1alpha.ValidationAttributes.policy:type_name -> octant.v1alpha.ValidationAttributes.PolicyEntry
	2,  // 9: octant.v1alpha.ConnectionService.GetConnectionStatus:input_type -> octant.v1alpha.GetConnectionStatusRequest
	0,  // 10: octant.v1alpha.ConnectionService.GenerateManifests:input_type -> octant.v1alpha.GenerateManifestsRequest
	3,  // 11: octant.v1alpha.ConnectionService.GetConnectionStatus:output_type -> octant.v1alpha.GetConnectionStatusResponse
	1,  // 12: octant.v1alpha.ConnectionService.GenerateManifests:output_type -> octant.v1alpha.GenerateManifestsResponse
	11, // [11:13] is the sub-list for method output_type
	9,  // [9:11] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_octant_v1alpha_connection_service_proto_init() }
func file_octant_v1alpha_connection_service_proto_init() {
	if File_octant_v1alpha_connection_service_proto != nil {
		return
	}
	file_octant_v1alpha_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octant_v1alpha_connection_service_proto_rawDesc), len(file_octant_v1alpha_connection_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_octant_v1alpha_connection_service_proto_goTypes,
		DependencyIndexes: file_octant_v1alpha_connection_service_proto_depIdxs,
		MessageInfos:      file_octant_v1alpha_connection_service_proto_msgTypes,
	}.Build()
	File_octant_v1alpha_connection_service_proto = out.File
	file_octant_v1alpha_connection_service_proto_goTypes = nil
	file_octant_v1alpha_connection_service_proto_depIdxs = nil
}
