// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: octant/v1alpha/datadog_service.proto

package octantv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetDatadogIntegrationByNameRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name contains name of the integration to retrieve
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatadogIntegrationByNameRequest) Reset() {
	*x = GetDatadogIntegrationByNameRequest{}
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatadogIntegrationByNameRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatadogIntegrationByNameRequest) ProtoMessage() {}

func (x *GetDatadogIntegrationByNameRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatadogIntegrationByNameRequest.ProtoReflect.Descriptor instead.
func (*GetDatadogIntegrationByNameRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_datadog_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetDatadogIntegrationByNameRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetDatadogIntegrationByNameResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// url is the datadog api url to send telemetry data to.
	Url           string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatadogIntegrationByNameResponse) Reset() {
	*x = GetDatadogIntegrationByNameResponse{}
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatadogIntegrationByNameResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatadogIntegrationByNameResponse) ProtoMessage() {}

func (x *GetDatadogIntegrationByNameResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatadogIntegrationByNameResponse.ProtoReflect.Descriptor instead.
func (*GetDatadogIntegrationByNameResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_datadog_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetDatadogIntegrationByNameResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type GetDatadogIntegrationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// names contains the list of integration names
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDatadogIntegrationsResponse) Reset() {
	*x = GetDatadogIntegrationsResponse{}
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDatadogIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDatadogIntegrationsResponse) ProtoMessage() {}

func (x *GetDatadogIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDatadogIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*GetDatadogIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_datadog_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetDatadogIntegrationsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SaveDatadogIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name contains name of the datadog integration to save
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// api_key is the 32-character api key generated from datadog.
	ApiKey string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	// site_host is the datadog api domain to send telemetry data to.
	SiteHost      string `protobuf:"bytes,4,opt,name=site_host,json=siteHost,proto3" json:"site_host,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveDatadogIntegrationRequest) Reset() {
	*x = SaveDatadogIntegrationRequest{}
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveDatadogIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveDatadogIntegrationRequest) ProtoMessage() {}

func (x *SaveDatadogIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveDatadogIntegrationRequest.ProtoReflect.Descriptor instead.
func (*SaveDatadogIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_datadog_service_proto_rawDescGZIP(), []int{3}
}

func (x *SaveDatadogIntegrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveDatadogIntegrationRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SaveDatadogIntegrationRequest) GetSiteHost() string {
	if x != nil {
		return x.SiteHost
	}
	return ""
}

var File_octant_v1alpha_datadog_service_proto protoreflect.FileDescriptor

const file_octant_v1alpha_datadog_service_proto_rawDesc = "" +
	"\n" +
	"$octant/v1alpha/datadog_service.proto\x12\x0eoctant.v1alpha\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"C\n" +
	"\"GetDatadogIntegrationByNameRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18dR\x04name\"?\n" +
	"#GetDatadogIntegrationByNameResponse\x12\x18\n" +
	"\x03url\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\x03url\"6\n" +
	"\x1eGetDatadogIntegrationsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"\xf5\x01\n" +
	"\x1dSaveDatadogIntegrationRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x03\x18dR\x04name\x12$\n" +
	"\aapi_key\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x98\x01 R\x06apiKey\x12\x8e\x01\n" +
	"\tsite_host\x18\x04 \x01(\tBq\xbaHn\xba\x01k\n" +
	"'SaveDatadogIntegrationRequest.site_host\x12-Site host must be a valid hostname, not a URI\x1a\x11this.isHostname()R\bsiteHost2\xe8\x02\n" +
	"\x0eDatadogService\x12e\n" +
	"\x16GetDatadogIntegrations\x12\x16.google.protobuf.Empty\x1a..octant.v1alpha.GetDatadogIntegrationsResponse\"\x03\x90\x02\x01\x12\x8b\x01\n" +
	"\x1bGetDatadogIntegrationByName\x122.octant.v1alpha.GetDatadogIntegrationByNameRequest\x1a3.octant.v1alpha.GetDatadogIntegrationByNameResponse\"\x03\x90\x02\x01\x12a\n" +
	"\x16SaveDatadogIntegration\x12-.octant.v1alpha.SaveDatadogIntegrationRequest\x1a\x16.google.protobuf.Empty\"\x00B\xce\x01\n" +
	"\x12com.octant.v1alphaB\x13DatadogServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha;octantv1alpha\xa2\x02\x03OXX\xaa\x02\x0eOctant.V1alpha\xca\x02\x0eOctant\\V1alpha\xe2\x02\x1aOctant\\V1alpha\\GPBMetadata\xea\x02\x0fOctant::V1alphab\x06proto3"

var (
	file_octant_v1alpha_datadog_service_proto_rawDescOnce sync.Once
	file_octant_v1alpha_datadog_service_proto_rawDescData []byte
)

func file_octant_v1alpha_datadog_service_proto_rawDescGZIP() []byte {
	file_octant_v1alpha_datadog_service_proto_rawDescOnce.Do(func() {
		file_octant_v1alpha_datadog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octant_v1alpha_datadog_service_proto_rawDesc), len(file_octant_v1alpha_datadog_service_proto_rawDesc)))
	})
	return file_octant_v1alpha_datadog_service_proto_rawDescData
}

var file_octant_v1alpha_datadog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_octant_v1alpha_datadog_service_proto_goTypes = []any{
	(*GetDatadogIntegrationByNameRequest)(nil),  // 0: octant.v1alpha.GetDatadogIntegrationByNameRequest
	(*GetDatadogIntegrationByNameResponse)(nil), // 1: octant.v1alpha.GetDatadogIntegrationByNameResponse
	(*GetDatadogIntegrationsResponse)(nil),      // 2: octant.v1alpha.GetDatadogIntegrationsResponse
	(*SaveDatadogIntegrationRequest)(nil),       // 3: octant.v1alpha.SaveDatadogIntegrationRequest
	(*emptypb.Empty)(nil),                       // 4: google.protobuf.Empty
}
var file_octant_v1alpha_datadog_service_proto_depIdxs = []int32{
	4, // 0: octant.v1alpha.DatadogService.GetDatadogIntegrations:input_type -> google.protobuf.Empty
	0, // 1: octant.v1alpha.DatadogService.GetDatadogIntegrationByName:input_type -> octant.v1alpha.GetDatadogIntegrationByNameRequest
	3, // 2: octant.v1alpha.DatadogService.SaveDatadogIntegration:input_type -> octant.v1alpha.SaveDatadogIntegrationRequest
	2, // 3: octant.v1alpha.DatadogService.GetDatadogIntegrations:output_type -> octant.v1alpha.GetDatadogIntegrationsResponse
	1, // 4: octant.v1alpha.DatadogService.GetDatadogIntegrationByName:output_type -> octant.v1alpha.GetDatadogIntegrationByNameResponse
	4, // 5: octant.v1alpha.DatadogService.SaveDatadogIntegration:output_type -> google.protobuf.Empty
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_octant_v1alpha_datadog_service_proto_init() }
func file_octant_v1alpha_datadog_service_proto_init() {
	if File_octant_v1alpha_datadog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octant_v1alpha_datadog_service_proto_rawDesc), len(file_octant_v1alpha_datadog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_octant_v1alpha_datadog_service_proto_goTypes,
		DependencyIndexes: file_octant_v1alpha_datadog_service_proto_depIdxs,
		MessageInfos:      file_octant_v1alpha_datadog_service_proto_msgTypes,
	}.Build()
	File_octant_v1alpha_datadog_service_proto = out.File
	file_octant_v1alpha_datadog_service_proto_goTypes = nil
	file_octant_v1alpha_datadog_service_proto_depIdxs = nil
}
