// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octant/v1alpha/datadog_service.proto

package octantv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetIntegrationsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// names contains the list of datadog integration names
	Names         []string `protobuf:"bytes,1,rep,name=names,proto3" json:"names,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetIntegrationsResponse) Reset() {
	*x = GetIntegrationsResponse{}
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetIntegrationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetIntegrationsResponse) ProtoMessage() {}

func (x *GetIntegrationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetIntegrationsResponse.ProtoReflect.Descriptor instead.
func (*GetIntegrationsResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_datadog_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetIntegrationsResponse) GetNames() []string {
	if x != nil {
		return x.Names
	}
	return nil
}

type SaveIntegrationRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name contains name of the datadog integration to save
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	ApiKey        string `protobuf:"bytes,2,opt,name=api_key,json=apiKey,proto3" json:"api_key,omitempty"`
	Url           string `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveIntegrationRequest) Reset() {
	*x = SaveIntegrationRequest{}
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveIntegrationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveIntegrationRequest) ProtoMessage() {}

func (x *SaveIntegrationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_datadog_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveIntegrationRequest.ProtoReflect.Descriptor instead.
func (*SaveIntegrationRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_datadog_service_proto_rawDescGZIP(), []int{1}
}

func (x *SaveIntegrationRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *SaveIntegrationRequest) GetApiKey() string {
	if x != nil {
		return x.ApiKey
	}
	return ""
}

func (x *SaveIntegrationRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

var File_octant_v1alpha_datadog_service_proto protoreflect.FileDescriptor

const file_octant_v1alpha_datadog_service_proto_rawDesc = "" +
	"\n" +
	"$octant/v1alpha/datadog_service.proto\x12\x0eoctant.v1alpha\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"/\n" +
	"\x17GetIntegrationsResponse\x12\x14\n" +
	"\x05names\x18\x01 \x03(\tR\x05names\"|\n" +
	"\x16SaveIntegrationRequest\x12\x1d\n" +
	"\x04name\x18\x01 \x01(\tB\t\xbaH\x06r\x04\x10\x05\x18dR\x04name\x12$\n" +
	"\aapi_key\x18\x02 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x98\x01 R\x06apiKey\x12\x1d\n" +
	"\x03url\x18\x03 \x01(\tB\v\xbaH\b\xc8\x01\x01r\x03\x80\x02\x01R\x03url2\xbb\x01\n" +
	"\x0eDatadogService\x12T\n" +
	"\x0fGetIntegrations\x12\x16.google.protobuf.Empty\x1a'.octant.v1alpha.GetIntegrationsResponse\"\x00\x12S\n" +
	"\x0fSaveIntegration\x12&.octant.v1alpha.SaveIntegrationRequest\x1a\x16.google.protobuf.Empty\"\x00B\xce\x01\n" +
	"\x12com.octant.v1alphaB\x13DatadogServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha;octantv1alpha\xa2\x02\x03OXX\xaa\x02\x0eOctant.V1alpha\xca\x02\x0eOctant\\V1alpha\xe2\x02\x1aOctant\\V1alpha\\GPBMetadata\xea\x02\x0fOctant::V1alphab\x06proto3"

var (
	file_octant_v1alpha_datadog_service_proto_rawDescOnce sync.Once
	file_octant_v1alpha_datadog_service_proto_rawDescData []byte
)

func file_octant_v1alpha_datadog_service_proto_rawDescGZIP() []byte {
	file_octant_v1alpha_datadog_service_proto_rawDescOnce.Do(func() {
		file_octant_v1alpha_datadog_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octant_v1alpha_datadog_service_proto_rawDesc), len(file_octant_v1alpha_datadog_service_proto_rawDesc)))
	})
	return file_octant_v1alpha_datadog_service_proto_rawDescData
}

var file_octant_v1alpha_datadog_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_octant_v1alpha_datadog_service_proto_goTypes = []any{
	(*GetIntegrationsResponse)(nil), // 0: octant.v1alpha.GetIntegrationsResponse
	(*SaveIntegrationRequest)(nil),  // 1: octant.v1alpha.SaveIntegrationRequest
	(*emptypb.Empty)(nil),           // 2: google.protobuf.Empty
}
var file_octant_v1alpha_datadog_service_proto_depIdxs = []int32{
	2, // 0: octant.v1alpha.DatadogService.GetIntegrations:input_type -> google.protobuf.Empty
	1, // 1: octant.v1alpha.DatadogService.SaveIntegration:input_type -> octant.v1alpha.SaveIntegrationRequest
	0, // 2: octant.v1alpha.DatadogService.GetIntegrations:output_type -> octant.v1alpha.GetIntegrationsResponse
	2, // 3: octant.v1alpha.DatadogService.SaveIntegration:output_type -> google.protobuf.Empty
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_octant_v1alpha_datadog_service_proto_init() }
func file_octant_v1alpha_datadog_service_proto_init() {
	if File_octant_v1alpha_datadog_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octant_v1alpha_datadog_service_proto_rawDesc), len(file_octant_v1alpha_datadog_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_octant_v1alpha_datadog_service_proto_goTypes,
		DependencyIndexes: file_octant_v1alpha_datadog_service_proto_depIdxs,
		MessageInfos:      file_octant_v1alpha_datadog_service_proto_msgTypes,
	}.Build()
	File_octant_v1alpha_datadog_service_proto = out.File
	file_octant_v1alpha_datadog_service_proto_goTypes = nil
	file_octant_v1alpha_datadog_service_proto_depIdxs = nil
}
