// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octant/v1alpha/install_service.proto

package octantv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InstallStatus int32

const (
	InstallStatus_INSTALL_STATUS_UNSPECIFIED InstallStatus = 0
	InstallStatus_INSTALL_STATUS_INSTALLING  InstallStatus = 1
	InstallStatus_INSTALL_STATUS_ERROR       InstallStatus = 2
	InstallStatus_INSTALL_STATUS_INSTALLED   InstallStatus = 3
)

// Enum value maps for InstallStatus.
var (
	InstallStatus_name = map[int32]string{
		0: "INSTALL_STATUS_UNSPECIFIED",
		1: "INSTALL_STATUS_INSTALLING",
		2: "INSTALL_STATUS_ERROR",
		3: "INSTALL_STATUS_INSTALLED",
	}
	InstallStatus_value = map[string]int32{
		"INSTALL_STATUS_UNSPECIFIED": 0,
		"INSTALL_STATUS_INSTALLING":  1,
		"INSTALL_STATUS_ERROR":       2,
		"INSTALL_STATUS_INSTALLED":   3,
	}
)

func (x InstallStatus) Enum() *InstallStatus {
	p := new(InstallStatus)
	*p = x
	return p
}

func (x InstallStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (InstallStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_octant_v1alpha_install_service_proto_enumTypes[0].Descriptor()
}

func (InstallStatus) Type() protoreflect.EnumType {
	return &file_octant_v1alpha_install_service_proto_enumTypes[0]
}

func (x InstallStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use InstallStatus.Descriptor instead.
func (InstallStatus) EnumDescriptor() ([]byte, []int) {
	return file_octant_v1alpha_install_service_proto_rawDescGZIP(), []int{0}
}

type InstallMDAIHubRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the named octant connection configuration to use for install.
	ConnectionName string `protobuf:"bytes,2,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	// mdai_version is the mdai hub version to use for install.
	MdaiVersion   string `protobuf:"bytes,3,opt,name=mdai_version,json=mdaiVersion,proto3" json:"mdai_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallMDAIHubRequest) Reset() {
	*x = InstallMDAIHubRequest{}
	mi := &file_octant_v1alpha_install_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallMDAIHubRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallMDAIHubRequest) ProtoMessage() {}

func (x *InstallMDAIHubRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_install_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallMDAIHubRequest.ProtoReflect.Descriptor instead.
func (*InstallMDAIHubRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_install_service_proto_rawDescGZIP(), []int{0}
}

func (x *InstallMDAIHubRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *InstallMDAIHubRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

func (x *InstallMDAIHubRequest) GetMdaiVersion() string {
	if x != nil {
		return x.MdaiVersion
	}
	return ""
}

type GetInstallStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// hub_name is the name of the mdai hub.
	HubName       string `protobuf:"bytes,1,opt,name=hub_name,json=hubName,proto3" json:"hub_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallStatusRequest) Reset() {
	*x = GetInstallStatusRequest{}
	mi := &file_octant_v1alpha_install_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallStatusRequest) ProtoMessage() {}

func (x *GetInstallStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_install_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallStatusRequest.ProtoReflect.Descriptor instead.
func (*GetInstallStatusRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_install_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetInstallStatusRequest) GetHubName() string {
	if x != nil {
		return x.HubName
	}
	return ""
}

type GetInstallStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// install_status is the status of the installation.
	InstallStatus InstallStatus `protobuf:"varint,1,opt,name=install_status,json=installStatus,proto3,enum=octant.v1alpha.InstallStatus" json:"install_status,omitempty"`
	// details will contain any necessary details for states that have extra information.
	Details       string `protobuf:"bytes,2,opt,name=details,proto3" json:"details,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInstallStatusResponse) Reset() {
	*x = GetInstallStatusResponse{}
	mi := &file_octant_v1alpha_install_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInstallStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInstallStatusResponse) ProtoMessage() {}

func (x *GetInstallStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_install_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInstallStatusResponse.ProtoReflect.Descriptor instead.
func (*GetInstallStatusResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_install_service_proto_rawDescGZIP(), []int{2}
}

func (x *GetInstallStatusResponse) GetInstallStatus() InstallStatus {
	if x != nil {
		return x.InstallStatus
	}
	return InstallStatus_INSTALL_STATUS_UNSPECIFIED
}

func (x *GetInstallStatusResponse) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

var File_octant_v1alpha_install_service_proto protoreflect.FileDescriptor

const file_octant_v1alpha_install_service_proto_rawDesc = "" +
	"\n" +
	"$octant/v1alpha/install_service.proto\x12\x0eoctant.v1alpha\x1a\x1bbuf/validate/validate.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x85\x02\n" +
	"\x15InstallMDAIHubRequest\x12I\n" +
	"\tnamespace\x18\x01 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12S\n" +
	"\x0fconnection_name\x18\x02 \x01(\tB*\xbaH'r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\x12L\n" +
	"\fmdai_version\x18\x03 \x01(\tB)\xbaH&r$2\"^(\\d+\\.\\d+\\.\\d+(-[a-z]*)?)|latest$R\vmdaiVersion\"<\n" +
	"\x17GetInstallStatusRequest\x12!\n" +
	"\bhub_name\x18\x01 \x01(\tB\x06\xbaH\x03\xc8\x01\x01R\ahubName\"\x82\x01\n" +
	"\x18GetInstallStatusResponse\x12L\n" +
	"\x0einstall_status\x18\x01 \x01(\x0e2\x1d.octant.v1alpha.InstallStatusB\x06\xbaH\x03\xc8\x01\x01R\rinstallStatus\x12\x18\n" +
	"\adetails\x18\x02 \x01(\tR\adetails*\x86\x01\n" +
	"\rInstallStatus\x12\x1e\n" +
	"\x1aINSTALL_STATUS_UNSPECIFIED\x10\x00\x12\x1d\n" +
	"\x19INSTALL_STATUS_INSTALLING\x10\x01\x12\x18\n" +
	"\x14INSTALL_STATUS_ERROR\x10\x02\x12\x1c\n" +
	"\x18INSTALL_STATUS_INSTALLED\x10\x032\xce\x01\n" +
	"\x0eInstallService\x12Q\n" +
	"\x0eInstallMDAIHub\x12%.octant.v1alpha.InstallMDAIHubRequest\x1a\x16.google.protobuf.Empty\"\x00\x12i\n" +
	"\x10GetInstallStatus\x12'.octant.v1alpha.GetInstallStatusRequest\x1a(.octant.v1alpha.GetInstallStatusResponse\"\x000\x01B\xce\x01\n" +
	"\x12com.octant.v1alphaB\x13InstallServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha;octantv1alpha\xa2\x02\x03OXX\xaa\x02\x0eOctant.V1alpha\xca\x02\x0eOctant\\V1alpha\xe2\x02\x1aOctant\\V1alpha\\GPBMetadata\xea\x02\x0fOctant::V1alphab\x06proto3"

var (
	file_octant_v1alpha_install_service_proto_rawDescOnce sync.Once
	file_octant_v1alpha_install_service_proto_rawDescData []byte
)

func file_octant_v1alpha_install_service_proto_rawDescGZIP() []byte {
	file_octant_v1alpha_install_service_proto_rawDescOnce.Do(func() {
		file_octant_v1alpha_install_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octant_v1alpha_install_service_proto_rawDesc), len(file_octant_v1alpha_install_service_proto_rawDesc)))
	})
	return file_octant_v1alpha_install_service_proto_rawDescData
}

var file_octant_v1alpha_install_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_octant_v1alpha_install_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_octant_v1alpha_install_service_proto_goTypes = []any{
	(InstallStatus)(0),               // 0: octant.v1alpha.InstallStatus
	(*InstallMDAIHubRequest)(nil),    // 1: octant.v1alpha.InstallMDAIHubRequest
	(*GetInstallStatusRequest)(nil),  // 2: octant.v1alpha.GetInstallStatusRequest
	(*GetInstallStatusResponse)(nil), // 3: octant.v1alpha.GetInstallStatusResponse
	(*emptypb.Empty)(nil),            // 4: google.protobuf.Empty
}
var file_octant_v1alpha_install_service_proto_depIdxs = []int32{
	0, // 0: octant.v1alpha.GetInstallStatusResponse.install_status:type_name -> octant.v1alpha.InstallStatus
	1, // 1: octant.v1alpha.InstallService.InstallMDAIHub:input_type -> octant.v1alpha.InstallMDAIHubRequest
	2, // 2: octant.v1alpha.InstallService.GetInstallStatus:input_type -> octant.v1alpha.GetInstallStatusRequest
	4, // 3: octant.v1alpha.InstallService.InstallMDAIHub:output_type -> google.protobuf.Empty
	3, // 4: octant.v1alpha.InstallService.GetInstallStatus:output_type -> octant.v1alpha.GetInstallStatusResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_octant_v1alpha_install_service_proto_init() }
func file_octant_v1alpha_install_service_proto_init() {
	if File_octant_v1alpha_install_service_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octant_v1alpha_install_service_proto_rawDesc), len(file_octant_v1alpha_install_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_octant_v1alpha_install_service_proto_goTypes,
		DependencyIndexes: file_octant_v1alpha_install_service_proto_depIdxs,
		EnumInfos:         file_octant_v1alpha_install_service_proto_enumTypes,
		MessageInfos:      file_octant_v1alpha_install_service_proto_msgTypes,
	}.Build()
	File_octant_v1alpha_install_service_proto = out.File
	file_octant_v1alpha_install_service_proto_goTypes = nil
	file_octant_v1alpha_install_service_proto_depIdxs = nil
}
