// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octant/v1alpha/setting_service.proto

package octantv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateResponse_Status int32

const (
	UpdateResponse_STATUS_UNSPECIFIED UpdateResponse_Status = 0
	// STATUS_UPDATING means we are still updating the configmap/secret with the given changes.
	UpdateResponse_STATUS_UPDATING UpdateResponse_Status = 1
	// STATUS_UPDATED means changes have been updated in the configmap/secret.
	UpdateResponse_STATUS_UPDATED UpdateResponse_Status = 2
	// STATUS_DEPLOY means we are deploying collectors to reflect the changes.
	UpdateResponse_STATUS_DEPLOY UpdateResponse_Status = 3
	// STATUS_WAIT means we are waiting for the collectors deployment to be complete.
	UpdateResponse_STATUS_WAIT UpdateResponse_Status = 4
	// STATUS_COMPLETED means update are complete.
	UpdateResponse_STATUS_COMPLETED UpdateResponse_Status = 5
	// STATUS_TIMEOUT means Octant timed out while waiting for collector to be deployed.
	// Note: This doesn't necessarily means the collectors aren't deployed.
	UpdateResponse_STATUS_TIMEOUT UpdateResponse_Status = 6
)

// Enum value maps for UpdateResponse_Status.
var (
	UpdateResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_UPDATING",
		2: "STATUS_UPDATED",
		3: "STATUS_DEPLOY",
		4: "STATUS_WAIT",
		5: "STATUS_COMPLETED",
		6: "STATUS_TIMEOUT",
	}
	UpdateResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED": 0,
		"STATUS_UPDATING":    1,
		"STATUS_UPDATED":     2,
		"STATUS_DEPLOY":      3,
		"STATUS_WAIT":        4,
		"STATUS_COMPLETED":   5,
		"STATUS_TIMEOUT":     6,
	}
)

func (x UpdateResponse_Status) Enum() *UpdateResponse_Status {
	p := new(UpdateResponse_Status)
	*p = x
	return p
}

func (x UpdateResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_octant_v1alpha_setting_service_proto_enumTypes[0].Descriptor()
}

func (UpdateResponse_Status) Type() protoreflect.EnumType {
	return &file_octant_v1alpha_setting_service_proto_enumTypes[0]
}

func (x UpdateResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateResponse_Status.Descriptor instead.
func (UpdateResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_octant_v1alpha_setting_service_proto_rawDescGZIP(), []int{1, 0}
}

type UpdateRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// scope indicates which connection to modify.
	Scope *ConnectionScope `protobuf:"bytes,1,opt,name=scope,proto3" json:"scope,omitempty"`
	// telemetry_types contains the new telemetry types to enable for the given connection.
	// If telemetry_types is empty, the connection's current telemetry_types will not be modified.
	// If telemetry_types is not empty, the octant connection cofigmap will be updated with the new telemetry_types,
	// lb collector will be updated to include relevant pipelines, and relevant sampling collectors will be spinned up/down.
	TelemetryTypes []MLTType `protobuf:"varint,2,rep,packed,name=telemetry_types,json=telemetryTypes,proto3,enum=octant.v1alpha.MLTType" json:"telemetry_types,omitempty"`
	// datadog_url contains the new datadog URL to be applied.
	// If datadog_url is empty, existing URL will not be modified.
	// If datadog_url is not empty, the datadog integration secret will be updated with the new URL,
	// and the sampling collectors will be restarted to use the new data.
	DatadogUrl string `protobuf:"bytes,3,opt,name=datadog_url,json=datadogUrl,proto3" json:"datadog_url,omitempty"`
	// datadog_api_key contains the new datadog API key to be applied.
	// If datadog_api_key is empty, existing API key will not be modified.
	// If datadog_api_key is not empty, the datadog integration secret will be updated with the new API key,
	// and the sampling collectors will be restarted to use the new data.
	DatadogApiKey string `protobuf:"bytes,4,opt,name=datadog_api_key,json=datadogApiKey,proto3" json:"datadog_api_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRequest) Reset() {
	*x = UpdateRequest{}
	mi := &file_octant_v1alpha_setting_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRequest) ProtoMessage() {}

func (x *UpdateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_setting_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRequest.ProtoReflect.Descriptor instead.
func (*UpdateRequest) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_setting_service_proto_rawDescGZIP(), []int{0}
}

func (x *UpdateRequest) GetScope() *ConnectionScope {
	if x != nil {
		return x.Scope
	}
	return nil
}

func (x *UpdateRequest) GetTelemetryTypes() []MLTType {
	if x != nil {
		return x.TelemetryTypes
	}
	return nil
}

func (x *UpdateRequest) GetDatadogUrl() string {
	if x != nil {
		return x.DatadogUrl
	}
	return ""
}

func (x *UpdateRequest) GetDatadogApiKey() string {
	if x != nil {
		return x.DatadogApiKey
	}
	return ""
}

type UpdateResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// status indicates current status of the update.
	// For more details, see comments in Status enum.
	Status        UpdateResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=octant.v1alpha.UpdateResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateResponse) Reset() {
	*x = UpdateResponse{}
	mi := &file_octant_v1alpha_setting_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateResponse) ProtoMessage() {}

func (x *UpdateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_octant_v1alpha_setting_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateResponse.ProtoReflect.Descriptor instead.
func (*UpdateResponse) Descriptor() ([]byte, []int) {
	return file_octant_v1alpha_setting_service_proto_rawDescGZIP(), []int{1}
}

func (x *UpdateResponse) GetStatus() UpdateResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateResponse_STATUS_UNSPECIFIED
}

var File_octant_v1alpha_setting_service_proto protoreflect.FileDescriptor

const file_octant_v1alpha_setting_service_proto_rawDesc = "" +
	"\n" +
	"$octant/v1alpha/setting_service.proto\x12\x0eoctant.v1alpha\x1a\x1bbuf/validate/validate.proto\x1a\x19octant/v1alpha/type.proto\"\xdf\x02\n" +
	"\rUpdateRequest\x12=\n" +
	"\x05scope\x18\x01 \x01(\v2\x1f.octant.v1alpha.ConnectionScopeB\x06\xbaH\x03\xc8\x01\x01R\x05scope\x12U\n" +
	"\x0ftelemetry_types\x18\x02 \x03(\x0e2\x17.octant.v1alpha.MLTTypeB\x13\xbaH\x10\x92\x01\r\x18\x01\"\t\x82\x01\x06\x10\x01 \x00 \x01R\x0etelemetryTypes\x12\x1f\n" +
	"\vdatadog_url\x18\x03 \x01(\tR\n" +
	"datadogUrl\x12\x96\x01\n" +
	"\x0fdatadog_api_key\x18\x04 \x01(\tBn\xbaHk\xba\x01h\n" +
	"\vempty_or_32\x124should either be empty or have exactly 32 characters\x1a#size(this) == 0 || size(this) == 32R\rdatadogApiKey\"\xe9\x01\n" +
	"\x0eUpdateResponse\x12=\n" +
	"\x06status\x18\x01 \x01(\x0e2%.octant.v1alpha.UpdateResponse.StatusR\x06status\"\x97\x01\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fSTATUS_UPDATING\x10\x01\x12\x12\n" +
	"\x0eSTATUS_UPDATED\x10\x02\x12\x11\n" +
	"\rSTATUS_DEPLOY\x10\x03\x12\x0f\n" +
	"\vSTATUS_WAIT\x10\x04\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x05\x12\x12\n" +
	"\x0eSTATUS_TIMEOUT\x10\x062]\n" +
	"\x0eSettingService\x12K\n" +
	"\x06Update\x12\x1d.octant.v1alpha.UpdateRequest\x1a\x1e.octant.v1alpha.UpdateResponse\"\x000\x01B\xce\x01\n" +
	"\x12com.octant.v1alphaB\x13SettingServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha;octantv1alpha\xa2\x02\x03OXX\xaa\x02\x0eOctant.V1alpha\xca\x02\x0eOctant\\V1alpha\xe2\x02\x1aOctant\\V1alpha\\GPBMetadata\xea\x02\x0fOctant::V1alphab\x06proto3"

var (
	file_octant_v1alpha_setting_service_proto_rawDescOnce sync.Once
	file_octant_v1alpha_setting_service_proto_rawDescData []byte
)

func file_octant_v1alpha_setting_service_proto_rawDescGZIP() []byte {
	file_octant_v1alpha_setting_service_proto_rawDescOnce.Do(func() {
		file_octant_v1alpha_setting_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octant_v1alpha_setting_service_proto_rawDesc), len(file_octant_v1alpha_setting_service_proto_rawDesc)))
	})
	return file_octant_v1alpha_setting_service_proto_rawDescData
}

var file_octant_v1alpha_setting_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_octant_v1alpha_setting_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_octant_v1alpha_setting_service_proto_goTypes = []any{
	(UpdateResponse_Status)(0), // 0: octant.v1alpha.UpdateResponse.Status
	(*UpdateRequest)(nil),      // 1: octant.v1alpha.UpdateRequest
	(*UpdateResponse)(nil),     // 2: octant.v1alpha.UpdateResponse
	(*ConnectionScope)(nil),    // 3: octant.v1alpha.ConnectionScope
	(MLTType)(0),               // 4: octant.v1alpha.MLTType
}
var file_octant_v1alpha_setting_service_proto_depIdxs = []int32{
	3, // 0: octant.v1alpha.UpdateRequest.scope:type_name -> octant.v1alpha.ConnectionScope
	4, // 1: octant.v1alpha.UpdateRequest.telemetry_types:type_name -> octant.v1alpha.MLTType
	0, // 2: octant.v1alpha.UpdateResponse.status:type_name -> octant.v1alpha.UpdateResponse.Status
	1, // 3: octant.v1alpha.SettingService.Update:input_type -> octant.v1alpha.UpdateRequest
	2, // 4: octant.v1alpha.SettingService.Update:output_type -> octant.v1alpha.UpdateResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_octant_v1alpha_setting_service_proto_init() }
func file_octant_v1alpha_setting_service_proto_init() {
	if File_octant_v1alpha_setting_service_proto != nil {
		return
	}
	file_octant_v1alpha_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octant_v1alpha_setting_service_proto_rawDesc), len(file_octant_v1alpha_setting_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_octant_v1alpha_setting_service_proto_goTypes,
		DependencyIndexes: file_octant_v1alpha_setting_service_proto_depIdxs,
		EnumInfos:         file_octant_v1alpha_setting_service_proto_enumTypes,
		MessageInfos:      file_octant_v1alpha_setting_service_proto_msgTypes,
	}.Build()
	File_octant_v1alpha_setting_service_proto = out.File
	file_octant_v1alpha_setting_service_proto_goTypes = nil
	file_octant_v1alpha_setting_service_proto_depIdxs = nil
}
