// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: octant/v1alpha/type.proto

package octantv1alpha

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ManifestOutFormat int32

const (
	ManifestOutFormat_MANIFEST_OUT_FORMAT_UNSPECIFIED ManifestOutFormat = 0
	ManifestOutFormat_MANIFEST_OUT_FORMAT_JSON        ManifestOutFormat = 1
	ManifestOutFormat_MANIFEST_OUT_FORMAT_YAML        ManifestOutFormat = 2
)

// Enum value maps for ManifestOutFormat.
var (
	ManifestOutFormat_name = map[int32]string{
		0: "MANIFEST_OUT_FORMAT_UNSPECIFIED",
		1: "MANIFEST_OUT_FORMAT_JSON",
		2: "MANIFEST_OUT_FORMAT_YAML",
	}
	ManifestOutFormat_value = map[string]int32{
		"MANIFEST_OUT_FORMAT_UNSPECIFIED": 0,
		"MANIFEST_OUT_FORMAT_JSON":        1,
		"MANIFEST_OUT_FORMAT_YAML":        2,
	}
)

func (x ManifestOutFormat) Enum() *ManifestOutFormat {
	p := new(ManifestOutFormat)
	*p = x
	return p
}

func (x ManifestOutFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ManifestOutFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_octant_v1alpha_type_proto_enumTypes[0].Descriptor()
}

func (ManifestOutFormat) Type() protoreflect.EnumType {
	return &file_octant_v1alpha_type_proto_enumTypes[0]
}

func (x ManifestOutFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ManifestOutFormat.Descriptor instead.
func (ManifestOutFormat) EnumDescriptor() ([]byte, []int) {
	return file_octant_v1alpha_type_proto_rawDescGZIP(), []int{0}
}

type MLTType int32

const (
	MLTType_MLT_TYPE_UNSPECIFIED MLTType = 0
	MLTType_MLT_TYPE_METRIC      MLTType = 1
	MLTType_MLT_TYPE_TRACE       MLTType = 2
	MLTType_MLT_TYPE_LOG         MLTType = 3
)

// Enum value maps for MLTType.
var (
	MLTType_name = map[int32]string{
		0: "MLT_TYPE_UNSPECIFIED",
		1: "MLT_TYPE_METRIC",
		2: "MLT_TYPE_TRACE",
		3: "MLT_TYPE_LOG",
	}
	MLTType_value = map[string]int32{
		"MLT_TYPE_UNSPECIFIED": 0,
		"MLT_TYPE_METRIC":      1,
		"MLT_TYPE_TRACE":       2,
		"MLT_TYPE_LOG":         3,
	}
)

func (x MLTType) Enum() *MLTType {
	p := new(MLTType)
	*p = x
	return p
}

func (x MLTType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MLTType) Descriptor() protoreflect.EnumDescriptor {
	return file_octant_v1alpha_type_proto_enumTypes[1].Descriptor()
}

func (MLTType) Type() protoreflect.EnumType {
	return &file_octant_v1alpha_type_proto_enumTypes[1]
}

func (x MLTType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MLTType.Descriptor instead.
func (MLTType) EnumDescriptor() ([]byte, []int) {
	return file_octant_v1alpha_type_proto_rawDescGZIP(), []int{1}
}

var File_octant_v1alpha_type_proto protoreflect.FileDescriptor

const file_octant_v1alpha_type_proto_rawDesc = "" +
	"\n" +
	"\x19octant/v1alpha/type.proto\x12\x0eoctant.v1alpha*t\n" +
	"\x11ManifestOutFormat\x12#\n" +
	"\x1fMANIFEST_OUT_FORMAT_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18MANIFEST_OUT_FORMAT_JSON\x10\x01\x12\x1c\n" +
	"\x18MANIFEST_OUT_FORMAT_YAML\x10\x02*^\n" +
	"\aMLTType\x12\x18\n" +
	"\x14MLT_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fMLT_TYPE_METRIC\x10\x01\x12\x12\n" +
	"\x0eMLT_TYPE_TRACE\x10\x02\x12\x10\n" +
	"\fMLT_TYPE_LOG\x10\x03B\xc4\x01\n" +
	"\x12com.octant.v1alphaB\tTypeProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/octant/v1alpha;octantv1alpha\xa2\x02\x03OXX\xaa\x02\x0eOctant.V1alpha\xca\x02\x0eOctant\\V1alpha\xe2\x02\x1aOctant\\V1alpha\\GPBMetadata\xea\x02\x0fOctant::V1alphab\x06proto3"

var (
	file_octant_v1alpha_type_proto_rawDescOnce sync.Once
	file_octant_v1alpha_type_proto_rawDescData []byte
)

func file_octant_v1alpha_type_proto_rawDescGZIP() []byte {
	file_octant_v1alpha_type_proto_rawDescOnce.Do(func() {
		file_octant_v1alpha_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_octant_v1alpha_type_proto_rawDesc), len(file_octant_v1alpha_type_proto_rawDesc)))
	})
	return file_octant_v1alpha_type_proto_rawDescData
}

var file_octant_v1alpha_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_octant_v1alpha_type_proto_goTypes = []any{
	(ManifestOutFormat)(0), // 0: octant.v1alpha.ManifestOutFormat
	(MLTType)(0),           // 1: octant.v1alpha.MLTType
}
var file_octant_v1alpha_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_octant_v1alpha_type_proto_init() }
func file_octant_v1alpha_type_proto_init() {
	if File_octant_v1alpha_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_octant_v1alpha_type_proto_rawDesc), len(file_octant_v1alpha_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_octant_v1alpha_type_proto_goTypes,
		DependencyIndexes: file_octant_v1alpha_type_proto_depIdxs,
		EnumInfos:         file_octant_v1alpha_type_proto_enumTypes,
	}.Build()
	File_octant_v1alpha_type_proto = out.File
	file_octant_v1alpha_type_proto_goTypes = nil
	file_octant_v1alpha_type_proto_depIdxs = nil
}
