// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: budget/v1alpha/budget_service.proto

package budgetv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// BudgetServiceName is the fully-qualified name of the BudgetService service.
	BudgetServiceName = "budget.v1alpha.BudgetService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// BudgetServiceOverallProcedure is the fully-qualified name of the BudgetService's Overall RPC.
	BudgetServiceOverallProcedure = "/budget.v1alpha.BudgetService/Overall"
	// BudgetServiceLogProcedure is the fully-qualified name of the BudgetService's Log RPC.
	BudgetServiceLogProcedure = "/budget.v1alpha.BudgetService/Log"
	// BudgetServiceTraceProcedure is the fully-qualified name of the BudgetService's Trace RPC.
	BudgetServiceTraceProcedure = "/budget.v1alpha.BudgetService/Trace"
)

// BudgetServiceClient is a client for the budget.v1alpha.BudgetService service.
type BudgetServiceClient interface {
	// Overall returns budeget stats.
	Overall(context.Context, *connect.Request[v1alpha.OverallRequest]) (*connect.Response[v1alpha.OverallResponse], error)
	// Log returns budeget stats for logs.
	Log(context.Context, *connect.Request[v1alpha.LogRequest]) (*connect.Response[v1alpha.LogResponse], error)
	// Trace returns budeget stats for traces.
	Trace(context.Context, *connect.Request[v1alpha.TraceRequest]) (*connect.Response[v1alpha.TraceResponse], error)
}

// NewBudgetServiceClient constructs a client for the budget.v1alpha.BudgetService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewBudgetServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) BudgetServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	budgetServiceMethods := v1alpha.File_budget_v1alpha_budget_service_proto.Services().ByName("BudgetService").Methods()
	return &budgetServiceClient{
		overall: connect.NewClient[v1alpha.OverallRequest, v1alpha.OverallResponse](
			httpClient,
			baseURL+BudgetServiceOverallProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("Overall")),
			connect.WithClientOptions(opts...),
		),
		log: connect.NewClient[v1alpha.LogRequest, v1alpha.LogResponse](
			httpClient,
			baseURL+BudgetServiceLogProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("Log")),
			connect.WithClientOptions(opts...),
		),
		trace: connect.NewClient[v1alpha.TraceRequest, v1alpha.TraceResponse](
			httpClient,
			baseURL+BudgetServiceTraceProcedure,
			connect.WithSchema(budgetServiceMethods.ByName("Trace")),
			connect.WithClientOptions(opts...),
		),
	}
}

// budgetServiceClient implements BudgetServiceClient.
type budgetServiceClient struct {
	overall *connect.Client[v1alpha.OverallRequest, v1alpha.OverallResponse]
	log     *connect.Client[v1alpha.LogRequest, v1alpha.LogResponse]
	trace   *connect.Client[v1alpha.TraceRequest, v1alpha.TraceResponse]
}

// Overall calls budget.v1alpha.BudgetService.Overall.
func (c *budgetServiceClient) Overall(ctx context.Context, req *connect.Request[v1alpha.OverallRequest]) (*connect.Response[v1alpha.OverallResponse], error) {
	return c.overall.CallUnary(ctx, req)
}

// Log calls budget.v1alpha.BudgetService.Log.
func (c *budgetServiceClient) Log(ctx context.Context, req *connect.Request[v1alpha.LogRequest]) (*connect.Response[v1alpha.LogResponse], error) {
	return c.log.CallUnary(ctx, req)
}

// Trace calls budget.v1alpha.BudgetService.Trace.
func (c *budgetServiceClient) Trace(ctx context.Context, req *connect.Request[v1alpha.TraceRequest]) (*connect.Response[v1alpha.TraceResponse], error) {
	return c.trace.CallUnary(ctx, req)
}

// BudgetServiceHandler is an implementation of the budget.v1alpha.BudgetService service.
type BudgetServiceHandler interface {
	// Overall returns budeget stats.
	Overall(context.Context, *connect.Request[v1alpha.OverallRequest]) (*connect.Response[v1alpha.OverallResponse], error)
	// Log returns budeget stats for logs.
	Log(context.Context, *connect.Request[v1alpha.LogRequest]) (*connect.Response[v1alpha.LogResponse], error)
	// Trace returns budeget stats for traces.
	Trace(context.Context, *connect.Request[v1alpha.TraceRequest]) (*connect.Response[v1alpha.TraceResponse], error)
}

// NewBudgetServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewBudgetServiceHandler(svc BudgetServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	budgetServiceMethods := v1alpha.File_budget_v1alpha_budget_service_proto.Services().ByName("BudgetService").Methods()
	budgetServiceOverallHandler := connect.NewUnaryHandler(
		BudgetServiceOverallProcedure,
		svc.Overall,
		connect.WithSchema(budgetServiceMethods.ByName("Overall")),
		connect.WithHandlerOptions(opts...),
	)
	budgetServiceLogHandler := connect.NewUnaryHandler(
		BudgetServiceLogProcedure,
		svc.Log,
		connect.WithSchema(budgetServiceMethods.ByName("Log")),
		connect.WithHandlerOptions(opts...),
	)
	budgetServiceTraceHandler := connect.NewUnaryHandler(
		BudgetServiceTraceProcedure,
		svc.Trace,
		connect.WithSchema(budgetServiceMethods.ByName("Trace")),
		connect.WithHandlerOptions(opts...),
	)
	return "/budget.v1alpha.BudgetService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case BudgetServiceOverallProcedure:
			budgetServiceOverallHandler.ServeHTTP(w, r)
		case BudgetServiceLogProcedure:
			budgetServiceLogHandler.ServeHTTP(w, r)
		case BudgetServiceTraceProcedure:
			budgetServiceTraceHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedBudgetServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedBudgetServiceHandler struct{}

func (UnimplementedBudgetServiceHandler) Overall(context.Context, *connect.Request[v1alpha.OverallRequest]) (*connect.Response[v1alpha.OverallResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("budget.v1alpha.BudgetService.Overall is not implemented"))
}

func (UnimplementedBudgetServiceHandler) Log(context.Context, *connect.Request[v1alpha.LogRequest]) (*connect.Response[v1alpha.LogResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("budget.v1alpha.BudgetService.Log is not implemented"))
}

func (UnimplementedBudgetServiceHandler) Trace(context.Context, *connect.Request[v1alpha.TraceRequest]) (*connect.Response[v1alpha.TraceResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("budget.v1alpha.BudgetService.Trace is not implemented"))
}
