// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: budget/v1alpha/filter_service.proto

package budgetv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// FilterServiceName is the fully-qualified name of the FilterService service.
	FilterServiceName = "budget.v1alpha.FilterService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// FilterServiceGetFilterProcedure is the fully-qualified name of the FilterService's GetFilter RPC.
	FilterServiceGetFilterProcedure = "/budget.v1alpha.FilterService/GetFilter"
	// FilterServiceUpdateFilterProcedure is the fully-qualified name of the FilterService's
	// UpdateFilter RPC.
	FilterServiceUpdateFilterProcedure = "/budget.v1alpha.FilterService/UpdateFilter"
)

// FilterServiceClient is a client for the budget.v1alpha.FilterService service.
type FilterServiceClient interface {
	// GetFilter returns the current filter setting of the given filter type.
	// If  an update is in progress, this will return with an error code `unavailable`.
	GetFilter(context.Context, *connect.Request[v1alpha.GetFilterRequest]) (*connect.Response[v1alpha.GetFilterResponse], error)
	// UpdateFilter attempts to update filter setting of the given filter type.
	// If an update is in progress, this will immediately return with an error code `unavailable`.
	// Otherwise, this will continuously give update until the update is complete or errored.
	UpdateFilter(context.Context, *connect.Request[v1alpha.UpdateFilterRequest]) (*connect.ServerStreamForClient[v1alpha.UpdateFilterResponse], error)
}

// NewFilterServiceClient constructs a client for the budget.v1alpha.FilterService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewFilterServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) FilterServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	filterServiceMethods := v1alpha.File_budget_v1alpha_filter_service_proto.Services().ByName("FilterService").Methods()
	return &filterServiceClient{
		getFilter: connect.NewClient[v1alpha.GetFilterRequest, v1alpha.GetFilterResponse](
			httpClient,
			baseURL+FilterServiceGetFilterProcedure,
			connect.WithSchema(filterServiceMethods.ByName("GetFilter")),
			connect.WithClientOptions(opts...),
		),
		updateFilter: connect.NewClient[v1alpha.UpdateFilterRequest, v1alpha.UpdateFilterResponse](
			httpClient,
			baseURL+FilterServiceUpdateFilterProcedure,
			connect.WithSchema(filterServiceMethods.ByName("UpdateFilter")),
			connect.WithClientOptions(opts...),
		),
	}
}

// filterServiceClient implements FilterServiceClient.
type filterServiceClient struct {
	getFilter    *connect.Client[v1alpha.GetFilterRequest, v1alpha.GetFilterResponse]
	updateFilter *connect.Client[v1alpha.UpdateFilterRequest, v1alpha.UpdateFilterResponse]
}

// GetFilter calls budget.v1alpha.FilterService.GetFilter.
func (c *filterServiceClient) GetFilter(ctx context.Context, req *connect.Request[v1alpha.GetFilterRequest]) (*connect.Response[v1alpha.GetFilterResponse], error) {
	return c.getFilter.CallUnary(ctx, req)
}

// UpdateFilter calls budget.v1alpha.FilterService.UpdateFilter.
func (c *filterServiceClient) UpdateFilter(ctx context.Context, req *connect.Request[v1alpha.UpdateFilterRequest]) (*connect.ServerStreamForClient[v1alpha.UpdateFilterResponse], error) {
	return c.updateFilter.CallServerStream(ctx, req)
}

// FilterServiceHandler is an implementation of the budget.v1alpha.FilterService service.
type FilterServiceHandler interface {
	// GetFilter returns the current filter setting of the given filter type.
	// If  an update is in progress, this will return with an error code `unavailable`.
	GetFilter(context.Context, *connect.Request[v1alpha.GetFilterRequest]) (*connect.Response[v1alpha.GetFilterResponse], error)
	// UpdateFilter attempts to update filter setting of the given filter type.
	// If an update is in progress, this will immediately return with an error code `unavailable`.
	// Otherwise, this will continuously give update until the update is complete or errored.
	UpdateFilter(context.Context, *connect.Request[v1alpha.UpdateFilterRequest], *connect.ServerStream[v1alpha.UpdateFilterResponse]) error
}

// NewFilterServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewFilterServiceHandler(svc FilterServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	filterServiceMethods := v1alpha.File_budget_v1alpha_filter_service_proto.Services().ByName("FilterService").Methods()
	filterServiceGetFilterHandler := connect.NewUnaryHandler(
		FilterServiceGetFilterProcedure,
		svc.GetFilter,
		connect.WithSchema(filterServiceMethods.ByName("GetFilter")),
		connect.WithHandlerOptions(opts...),
	)
	filterServiceUpdateFilterHandler := connect.NewServerStreamHandler(
		FilterServiceUpdateFilterProcedure,
		svc.UpdateFilter,
		connect.WithSchema(filterServiceMethods.ByName("UpdateFilter")),
		connect.WithHandlerOptions(opts...),
	)
	return "/budget.v1alpha.FilterService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case FilterServiceGetFilterProcedure:
			filterServiceGetFilterHandler.ServeHTTP(w, r)
		case FilterServiceUpdateFilterProcedure:
			filterServiceUpdateFilterHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedFilterServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedFilterServiceHandler struct{}

func (UnimplementedFilterServiceHandler) GetFilter(context.Context, *connect.Request[v1alpha.GetFilterRequest]) (*connect.Response[v1alpha.GetFilterResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("budget.v1alpha.FilterService.GetFilter is not implemented"))
}

func (UnimplementedFilterServiceHandler) UpdateFilter(context.Context, *connect.Request[v1alpha.UpdateFilterRequest], *connect.ServerStream[v1alpha.UpdateFilterResponse]) error {
	return connect.NewError(connect.CodeUnimplemented, errors.New("budget.v1alpha.FilterService.UpdateFilter is not implemented"))
}
