// Code generated by protoc-gen-connect-go. DO NOT EDIT.
//
// Source: budget/v1alpha/timeframe_service.proto

package budgetv1alphaconnect

import (
	connect "connectrpc.com/connect"
	context "context"
	errors "errors"
	v1alpha "github.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	http "net/http"
	strings "strings"
)

// This is a compile-time assertion to ensure that this generated file and the connect package are
// compatible. If you get a compiler error that this constant is not defined, this code was
// generated with a version of connect newer than the one compiled into your binary. You can fix the
// problem by either regenerating this code with an older version of connect or updating the connect
// version compiled into your binary.
const _ = connect.IsAtLeastVersion1_13_0

const (
	// TimeframeServiceName is the fully-qualified name of the TimeframeService service.
	TimeframeServiceName = "budget.v1alpha.TimeframeService"
)

// These constants are the fully-qualified names of the RPCs defined in this package. They're
// exposed at runtime as Spec.Procedure and as the final two segments of the HTTP route.
//
// Note that these are different from the fully-qualified method names used by
// google.golang.org/protobuf/reflect/protoreflect. To convert from these constants to
// reflection-formatted method names, remove the leading slash and convert the remaining slash to a
// period.
const (
	// TimeframeServiceTimeframeStatusProcedure is the fully-qualified name of the TimeframeService's
	// TimeframeStatus RPC.
	TimeframeServiceTimeframeStatusProcedure = "/budget.v1alpha.TimeframeService/TimeframeStatus"
)

// TimeframeServiceClient is a client for the budget.v1alpha.TimeframeService service.
type TimeframeServiceClient interface {
	// TimeframeStatus returns timeframe status for each timeframe.
	TimeframeStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.TimeframeStatusResponse], error)
}

// NewTimeframeServiceClient constructs a client for the budget.v1alpha.TimeframeService service. By
// default, it uses the Connect protocol with the binary Protobuf Codec, asks for gzipped responses,
// and sends uncompressed requests. To use the gRPC or gRPC-Web protocols, supply the
// connect.WithGRPC() or connect.WithGRPCWeb() options.
//
// The URL supplied here should be the base URL for the Connect or gRPC server (for example,
// http://api.acme.com or https://acme.com/grpc).
func NewTimeframeServiceClient(httpClient connect.HTTPClient, baseURL string, opts ...connect.ClientOption) TimeframeServiceClient {
	baseURL = strings.TrimRight(baseURL, "/")
	timeframeServiceMethods := v1alpha.File_budget_v1alpha_timeframe_service_proto.Services().ByName("TimeframeService").Methods()
	return &timeframeServiceClient{
		timeframeStatus: connect.NewClient[emptypb.Empty, v1alpha.TimeframeStatusResponse](
			httpClient,
			baseURL+TimeframeServiceTimeframeStatusProcedure,
			connect.WithSchema(timeframeServiceMethods.ByName("TimeframeStatus")),
			connect.WithClientOptions(opts...),
		),
	}
}

// timeframeServiceClient implements TimeframeServiceClient.
type timeframeServiceClient struct {
	timeframeStatus *connect.Client[emptypb.Empty, v1alpha.TimeframeStatusResponse]
}

// TimeframeStatus calls budget.v1alpha.TimeframeService.TimeframeStatus.
func (c *timeframeServiceClient) TimeframeStatus(ctx context.Context, req *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.TimeframeStatusResponse], error) {
	return c.timeframeStatus.CallUnary(ctx, req)
}

// TimeframeServiceHandler is an implementation of the budget.v1alpha.TimeframeService service.
type TimeframeServiceHandler interface {
	// TimeframeStatus returns timeframe status for each timeframe.
	TimeframeStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.TimeframeStatusResponse], error)
}

// NewTimeframeServiceHandler builds an HTTP handler from the service implementation. It returns the
// path on which to mount the handler and the handler itself.
//
// By default, handlers support the Connect, gRPC, and gRPC-Web protocols with the binary Protobuf
// and JSON codecs. They also support gzip compression.
func NewTimeframeServiceHandler(svc TimeframeServiceHandler, opts ...connect.HandlerOption) (string, http.Handler) {
	timeframeServiceMethods := v1alpha.File_budget_v1alpha_timeframe_service_proto.Services().ByName("TimeframeService").Methods()
	timeframeServiceTimeframeStatusHandler := connect.NewUnaryHandler(
		TimeframeServiceTimeframeStatusProcedure,
		svc.TimeframeStatus,
		connect.WithSchema(timeframeServiceMethods.ByName("TimeframeStatus")),
		connect.WithHandlerOptions(opts...),
	)
	return "/budget.v1alpha.TimeframeService/", http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		switch r.URL.Path {
		case TimeframeServiceTimeframeStatusProcedure:
			timeframeServiceTimeframeStatusHandler.ServeHTTP(w, r)
		default:
			http.NotFound(w, r)
		}
	})
}

// UnimplementedTimeframeServiceHandler returns CodeUnimplemented from all methods.
type UnimplementedTimeframeServiceHandler struct{}

func (UnimplementedTimeframeServiceHandler) TimeframeStatus(context.Context, *connect.Request[emptypb.Empty]) (*connect.Response[v1alpha.TimeframeStatusResponse], error) {
	return nil, connect.NewError(connect.CodeUnimplemented, errors.New("budget.v1alpha.TimeframeService.TimeframeStatus is not implemented"))
}
