// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: budget/v1alpha/budget_service.proto

package budgetv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OverallRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeframe tells the server timeframe of the data to retrieve.
	Timeframe Timeframe `protobuf:"varint,1,opt,name=timeframe,proto3,enum=budget.v1alpha.Timeframe" json:"timeframe,omitempty"`
	// namespace is the kubernetes namespace to install into.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverallRequest) Reset() {
	*x = OverallRequest{}
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallRequest) ProtoMessage() {}

func (x *OverallRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallRequest.ProtoReflect.Descriptor instead.
func (*OverallRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_budget_service_proto_rawDescGZIP(), []int{0}
}

func (x *OverallRequest) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *OverallRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type OverallResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Overall               `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OverallResponse) Reset() {
	*x = OverallResponse{}
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OverallResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OverallResponse) ProtoMessage() {}

func (x *OverallResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OverallResponse.ProtoReflect.Descriptor instead.
func (*OverallResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_budget_service_proto_rawDescGZIP(), []int{1}
}

func (x *OverallResponse) GetData() *Overall {
	if x != nil {
		return x.Data
	}
	return nil
}

type LogRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeframe tells the server timeframe of the data to retrieve.
	Timeframe Timeframe `protobuf:"varint,1,opt,name=timeframe,proto3,enum=budget.v1alpha.Timeframe" json:"timeframe,omitempty"`
	// size limits number of services to retrieve.
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// page_token (pagination) used to grab next page of data.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// search is used to filter the data so that only services with name containing the given search term will be returned.
	Search string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,6,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LogRequest) Reset() {
	*x = LogRequest{}
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRequest) ProtoMessage() {}

func (x *LogRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRequest.ProtoReflect.Descriptor instead.
func (*LogRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_budget_service_proto_rawDescGZIP(), []int{2}
}

func (x *LogRequest) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *LogRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *LogRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *LogRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *LogRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *LogRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

type LogResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Log                 `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogResponse) Reset() {
	*x = LogResponse{}
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogResponse) ProtoMessage() {}

func (x *LogResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogResponse.ProtoReflect.Descriptor instead.
func (*LogResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_budget_service_proto_rawDescGZIP(), []int{3}
}

func (x *LogResponse) GetData() []*Log {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *LogResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

type TraceRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeframe tells the server timeframe of the data to retrieve.
	Timeframe Timeframe `protobuf:"varint,1,opt,name=timeframe,proto3,enum=budget.v1alpha.Timeframe" json:"timeframe,omitempty"`
	// size limits number of trace root spans to retrieve.
	Size uint32 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	// page_token (pagination) used to grab next page of data.
	PageToken string `protobuf:"bytes,3,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	// search is used to filter the data so that only trace root span with name containing the given search term will be returned.
	Search string `protobuf:"bytes,4,opt,name=search,proto3" json:"search,omitempty"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,5,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,6,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TraceRequest) Reset() {
	*x = TraceRequest{}
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceRequest) ProtoMessage() {}

func (x *TraceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceRequest.ProtoReflect.Descriptor instead.
func (*TraceRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_budget_service_proto_rawDescGZIP(), []int{4}
}

func (x *TraceRequest) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *TraceRequest) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TraceRequest) GetPageToken() string {
	if x != nil {
		return x.PageToken
	}
	return ""
}

func (x *TraceRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *TraceRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *TraceRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

type TraceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Span                `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TraceResponse) Reset() {
	*x = TraceResponse{}
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TraceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TraceResponse) ProtoMessage() {}

func (x *TraceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_budget_service_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TraceResponse.ProtoReflect.Descriptor instead.
func (*TraceResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_budget_service_proto_rawDescGZIP(), []int{5}
}

func (x *TraceResponse) GetData() []*Span {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *TraceResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

var File_budget_v1alpha_budget_service_proto protoreflect.FileDescriptor

const file_budget_v1alpha_budget_service_proto_rawDesc = "" +
	"\n" +
	"#budget/v1alpha/budget_service.proto\x12\x0ebudget.v1alpha\x1a\x19budget/v1alpha/type.proto\x1a\x1bbuf/validate/validate.proto\"\xa3\x01\n" +
	"\x0eOverallRequest\x12F\n" +
	"\ttimeframe\x18\x01 \x01(\x0e2\x19.budget.v1alpha.TimeframeB\r\xbaH\n" +
	"\xc8\x01\x01\x82\x01\x04\x10\x01 \x00R\ttimeframe\x12I\n" +
	"\tnamespace\x18\x02 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\">\n" +
	"\x0fOverallResponse\x12+\n" +
	"\x04data\x18\x01 \x01(\v2\x17.budget.v1alpha.OverallR\x04data\"\xda\x02\n" +
	"\n" +
	"LogRequest\x12F\n" +
	"\ttimeframe\x18\x01 \x01(\x0e2\x19.budget.v1alpha.TimeframeB\r\xbaH\n" +
	"\xc8\x01\x01\x82\x01\x04\x10\x01 \x00R\ttimeframe\x12!\n" +
	"\x04size\x18\x02 \x01(\rB\r\xbaH\n" +
	"\xc8\x01\x01*\x05\x10\xfb\x01 \x00R\x04size\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\x06search\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18dR\x06search\x12I\n" +
	"\tnamespace\x18\x05 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12V\n" +
	"\x0fconnection_name\x18\x06 \x01(\tB-\xbaH*\xc8\x01\x01r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\"^\n" +
	"\vLogResponse\x12'\n" +
	"\x04data\x18\x01 \x03(\v2\x13.budget.v1alpha.LogR\x04data\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"\xdc\x02\n" +
	"\fTraceRequest\x12F\n" +
	"\ttimeframe\x18\x01 \x01(\x0e2\x19.budget.v1alpha.TimeframeB\r\xbaH\n" +
	"\xc8\x01\x01\x82\x01\x04\x10\x01 \x00R\ttimeframe\x12!\n" +
	"\x04size\x18\x02 \x01(\rB\r\xbaH\n" +
	"\xc8\x01\x01*\x05\x10\xfb\x01 \x00R\x04size\x12\x1d\n" +
	"\n" +
	"page_token\x18\x03 \x01(\tR\tpageToken\x12\x1f\n" +
	"\x06search\x18\x04 \x01(\tB\a\xbaH\x04r\x02\x18dR\x06search\x12I\n" +
	"\tnamespace\x18\x05 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12V\n" +
	"\x0fconnection_name\x18\x06 \x01(\tB-\xbaH*\xc8\x01\x01r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\"a\n" +
	"\rTraceResponse\x12(\n" +
	"\x04data\x18\x01 \x03(\v2\x14.budget.v1alpha.SpanR\x04data\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken2\xf0\x01\n" +
	"\rBudgetService\x12O\n" +
	"\aOverall\x12\x1e.budget.v1alpha.OverallRequest\x1a\x1f.budget.v1alpha.OverallResponse\"\x03\x90\x02\x01\x12C\n" +
	"\x03Log\x12\x1a.budget.v1alpha.LogRequest\x1a\x1b.budget.v1alpha.LogResponse\"\x03\x90\x02\x01\x12I\n" +
	"\x05Trace\x12\x1c.budget.v1alpha.TraceRequest\x1a\x1d.budget.v1alpha.TraceResponse\"\x03\x90\x02\x01B\xcd\x01\n" +
	"\x12com.budget.v1alphaB\x12BudgetServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha;budgetv1alpha\xa2\x02\x03BXX\xaa\x02\x0eBudget.V1alpha\xca\x02\x0eBudget\\V1alpha\xe2\x02\x1aBudget\\V1alpha\\GPBMetadata\xea\x02\x0fBudget::V1alphab\x06proto3"

var (
	file_budget_v1alpha_budget_service_proto_rawDescOnce sync.Once
	file_budget_v1alpha_budget_service_proto_rawDescData []byte
)

func file_budget_v1alpha_budget_service_proto_rawDescGZIP() []byte {
	file_budget_v1alpha_budget_service_proto_rawDescOnce.Do(func() {
		file_budget_v1alpha_budget_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_budget_v1alpha_budget_service_proto_rawDesc), len(file_budget_v1alpha_budget_service_proto_rawDesc)))
	})
	return file_budget_v1alpha_budget_service_proto_rawDescData
}

var file_budget_v1alpha_budget_service_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_budget_v1alpha_budget_service_proto_goTypes = []any{
	(*OverallRequest)(nil),  // 0: budget.v1alpha.OverallRequest
	(*OverallResponse)(nil), // 1: budget.v1alpha.OverallResponse
	(*LogRequest)(nil),      // 2: budget.v1alpha.LogRequest
	(*LogResponse)(nil),     // 3: budget.v1alpha.LogResponse
	(*TraceRequest)(nil),    // 4: budget.v1alpha.TraceRequest
	(*TraceResponse)(nil),   // 5: budget.v1alpha.TraceResponse
	(Timeframe)(0),          // 6: budget.v1alpha.Timeframe
	(*Overall)(nil),         // 7: budget.v1alpha.Overall
	(*Log)(nil),             // 8: budget.v1alpha.Log
	(*Span)(nil),            // 9: budget.v1alpha.Span
}
var file_budget_v1alpha_budget_service_proto_depIdxs = []int32{
	6, // 0: budget.v1alpha.OverallRequest.timeframe:type_name -> budget.v1alpha.Timeframe
	7, // 1: budget.v1alpha.OverallResponse.data:type_name -> budget.v1alpha.Overall
	6, // 2: budget.v1alpha.LogRequest.timeframe:type_name -> budget.v1alpha.Timeframe
	8, // 3: budget.v1alpha.LogResponse.data:type_name -> budget.v1alpha.Log
	6, // 4: budget.v1alpha.TraceRequest.timeframe:type_name -> budget.v1alpha.Timeframe
	9, // 5: budget.v1alpha.TraceResponse.data:type_name -> budget.v1alpha.Span
	0, // 6: budget.v1alpha.BudgetService.Overall:input_type -> budget.v1alpha.OverallRequest
	2, // 7: budget.v1alpha.BudgetService.Log:input_type -> budget.v1alpha.LogRequest
	4, // 8: budget.v1alpha.BudgetService.Trace:input_type -> budget.v1alpha.TraceRequest
	1, // 9: budget.v1alpha.BudgetService.Overall:output_type -> budget.v1alpha.OverallResponse
	3, // 10: budget.v1alpha.BudgetService.Log:output_type -> budget.v1alpha.LogResponse
	5, // 11: budget.v1alpha.BudgetService.Trace:output_type -> budget.v1alpha.TraceResponse
	9, // [9:12] is the sub-list for method output_type
	6, // [6:9] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_budget_v1alpha_budget_service_proto_init() }
func file_budget_v1alpha_budget_service_proto_init() {
	if File_budget_v1alpha_budget_service_proto != nil {
		return
	}
	file_budget_v1alpha_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_budget_v1alpha_budget_service_proto_rawDesc), len(file_budget_v1alpha_budget_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_budget_v1alpha_budget_service_proto_goTypes,
		DependencyIndexes: file_budget_v1alpha_budget_service_proto_depIdxs,
		MessageInfos:      file_budget_v1alpha_budget_service_proto_msgTypes,
	}.Build()
	File_budget_v1alpha_budget_service_proto = out.File
	file_budget_v1alpha_budget_service_proto_goTypes = nil
	file_budget_v1alpha_budget_service_proto_depIdxs = nil
}
