// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: budget/v1alpha/filter_service.proto

package budgetv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UpdateFilterResponse_Status int32

const (
	UpdateFilterResponse_STATUS_UNSPECIFIED UpdateFilterResponse_Status = 0
	// STATUS_VALUE_UPDATED means the data have been updated in MDAI gateway.
	UpdateFilterResponse_STATUS_VALUE_UPDATED UpdateFilterResponse_Status = 1
	// STATUS_WAIT_PROPAGATION means we are waiting for the collectors to restart with the new values.
	UpdateFilterResponse_STATUS_WAIT_PROPAGATION UpdateFilterResponse_Status = 2
	// STATUS_COMPLETED means collectors are all updated.
	UpdateFilterResponse_STATUS_COMPLETED UpdateFilterResponse_Status = 3
)

// Enum value maps for UpdateFilterResponse_Status.
var (
	UpdateFilterResponse_Status_name = map[int32]string{
		0: "STATUS_UNSPECIFIED",
		1: "STATUS_VALUE_UPDATED",
		2: "STATUS_WAIT_PROPAGATION",
		3: "STATUS_COMPLETED",
	}
	UpdateFilterResponse_Status_value = map[string]int32{
		"STATUS_UNSPECIFIED":      0,
		"STATUS_VALUE_UPDATED":    1,
		"STATUS_WAIT_PROPAGATION": 2,
		"STATUS_COMPLETED":        3,
	}
)

func (x UpdateFilterResponse_Status) Enum() *UpdateFilterResponse_Status {
	p := new(UpdateFilterResponse_Status)
	*p = x
	return p
}

func (x UpdateFilterResponse_Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UpdateFilterResponse_Status) Descriptor() protoreflect.EnumDescriptor {
	return file_budget_v1alpha_filter_service_proto_enumTypes[0].Descriptor()
}

func (UpdateFilterResponse_Status) Type() protoreflect.EnumType {
	return &file_budget_v1alpha_filter_service_proto_enumTypes[0]
}

func (x UpdateFilterResponse_Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UpdateFilterResponse_Status.Descriptor instead.
func (UpdateFilterResponse_Status) EnumDescriptor() ([]byte, []int) {
	return file_budget_v1alpha_filter_service_proto_rawDescGZIP(), []int{3, 0}
}

type GetFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type contains the type of the filter to retrieve.
	Type FilterType `protobuf:"varint,1,opt,name=type,proto3,enum=budget.v1alpha.FilterType" json:"type,omitempty"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,3,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *GetFilterRequest) Reset() {
	*x = GetFilterRequest{}
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilterRequest) ProtoMessage() {}

func (x *GetFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilterRequest.ProtoReflect.Descriptor instead.
func (*GetFilterRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_filter_service_proto_rawDescGZIP(), []int{0}
}

func (x *GetFilterRequest) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_FILTER_TYPE_UNSPECIFIED
}

func (x *GetFilterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *GetFilterRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

type GetFilterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Filter                `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFilterResponse) Reset() {
	*x = GetFilterResponse{}
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFilterResponse) ProtoMessage() {}

func (x *GetFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFilterResponse.ProtoReflect.Descriptor instead.
func (*GetFilterResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_filter_service_proto_rawDescGZIP(), []int{1}
}

func (x *GetFilterResponse) GetData() *Filter {
	if x != nil {
		return x.Data
	}
	return nil
}

type UpdateFilterRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// data contains the filter setting data to update.
	// `type` indicates which filter type should be updated.
	Data *Filter `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	// namespace is the kubernetes namespace to install into.
	Namespace string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,3,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateFilterRequest) Reset() {
	*x = UpdateFilterRequest{}
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilterRequest) ProtoMessage() {}

func (x *UpdateFilterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilterRequest.ProtoReflect.Descriptor instead.
func (*UpdateFilterRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_filter_service_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateFilterRequest) GetData() *Filter {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *UpdateFilterRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *UpdateFilterRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

type UpdateFilterResponse struct {
	state         protoimpl.MessageState      `protogen:"open.v1"`
	Status        UpdateFilterResponse_Status `protobuf:"varint,1,opt,name=status,proto3,enum=budget.v1alpha.UpdateFilterResponse_Status" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateFilterResponse) Reset() {
	*x = UpdateFilterResponse{}
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateFilterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateFilterResponse) ProtoMessage() {}

func (x *UpdateFilterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_filter_service_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateFilterResponse.ProtoReflect.Descriptor instead.
func (*UpdateFilterResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_filter_service_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateFilterResponse) GetStatus() UpdateFilterResponse_Status {
	if x != nil {
		return x.Status
	}
	return UpdateFilterResponse_STATUS_UNSPECIFIED
}

var File_budget_v1alpha_filter_service_proto protoreflect.FileDescriptor

const file_budget_v1alpha_filter_service_proto_rawDesc = "" +
	"\n" +
	"#budget/v1alpha/filter_service.proto\x12\x0ebudget.v1alpha\x1a\x19budget/v1alpha/type.proto\x1a\x1bbuf/validate/validate.proto\"\xef\x01\n" +
	"\x10GetFilterRequest\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.budget.v1alpha.FilterTypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x04type\x12I\n" +
	"\tnamespace\x18\x02 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12S\n" +
	"\x0fconnection_name\x18\x03 \x01(\tB*\xbaH'r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\"?\n" +
	"\x11GetFilterResponse\x12*\n" +
	"\x04data\x18\x01 \x01(\v2\x16.budget.v1alpha.FilterR\x04data\"\xe9\x01\n" +
	"\x13UpdateFilterRequest\x122\n" +
	"\x04data\x18\x01 \x01(\v2\x16.budget.v1alpha.FilterB\x06\xbaH\x03\xc8\x01\x01R\x04data\x12I\n" +
	"\tnamespace\x18\x02 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\x12S\n" +
	"\x0fconnection_name\x18\x03 \x01(\tB*\xbaH'r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\"\xca\x01\n" +
	"\x14UpdateFilterResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.budget.v1alpha.UpdateFilterResponse.StatusR\x06status\"m\n" +
	"\x06Status\x12\x16\n" +
	"\x12STATUS_UNSPECIFIED\x10\x00\x12\x18\n" +
	"\x14STATUS_VALUE_UPDATED\x10\x01\x12\x1b\n" +
	"\x17STATUS_WAIT_PROPAGATION\x10\x02\x12\x14\n" +
	"\x10STATUS_COMPLETED\x10\x032\xc2\x01\n" +
	"\rFilterService\x12R\n" +
	"\tGetFilter\x12 .budget.v1alpha.GetFilterRequest\x1a!.budget.v1alpha.GetFilterResponse\"\x00\x12]\n" +
	"\fUpdateFilter\x12#.budget.v1alpha.UpdateFilterRequest\x1a$.budget.v1alpha.UpdateFilterResponse\"\x000\x01B\xcd\x01\n" +
	"\x12com.budget.v1alphaB\x12FilterServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha;budgetv1alpha\xa2\x02\x03BXX\xaa\x02\x0eBudget.V1alpha\xca\x02\x0eBudget\\V1alpha\xe2\x02\x1aBudget\\V1alpha\\GPBMetadata\xea\x02\x0fBudget::V1alphab\x06proto3"

var (
	file_budget_v1alpha_filter_service_proto_rawDescOnce sync.Once
	file_budget_v1alpha_filter_service_proto_rawDescData []byte
)

func file_budget_v1alpha_filter_service_proto_rawDescGZIP() []byte {
	file_budget_v1alpha_filter_service_proto_rawDescOnce.Do(func() {
		file_budget_v1alpha_filter_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_budget_v1alpha_filter_service_proto_rawDesc), len(file_budget_v1alpha_filter_service_proto_rawDesc)))
	})
	return file_budget_v1alpha_filter_service_proto_rawDescData
}

var file_budget_v1alpha_filter_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_budget_v1alpha_filter_service_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_budget_v1alpha_filter_service_proto_goTypes = []any{
	(UpdateFilterResponse_Status)(0), // 0: budget.v1alpha.UpdateFilterResponse.Status
	(*GetFilterRequest)(nil),         // 1: budget.v1alpha.GetFilterRequest
	(*GetFilterResponse)(nil),        // 2: budget.v1alpha.GetFilterResponse
	(*UpdateFilterRequest)(nil),      // 3: budget.v1alpha.UpdateFilterRequest
	(*UpdateFilterResponse)(nil),     // 4: budget.v1alpha.UpdateFilterResponse
	(FilterType)(0),                  // 5: budget.v1alpha.FilterType
	(*Filter)(nil),                   // 6: budget.v1alpha.Filter
}
var file_budget_v1alpha_filter_service_proto_depIdxs = []int32{
	5, // 0: budget.v1alpha.GetFilterRequest.type:type_name -> budget.v1alpha.FilterType
	6, // 1: budget.v1alpha.GetFilterResponse.data:type_name -> budget.v1alpha.Filter
	6, // 2: budget.v1alpha.UpdateFilterRequest.data:type_name -> budget.v1alpha.Filter
	0, // 3: budget.v1alpha.UpdateFilterResponse.status:type_name -> budget.v1alpha.UpdateFilterResponse.Status
	1, // 4: budget.v1alpha.FilterService.GetFilter:input_type -> budget.v1alpha.GetFilterRequest
	3, // 5: budget.v1alpha.FilterService.UpdateFilter:input_type -> budget.v1alpha.UpdateFilterRequest
	2, // 6: budget.v1alpha.FilterService.GetFilter:output_type -> budget.v1alpha.GetFilterResponse
	4, // 7: budget.v1alpha.FilterService.UpdateFilter:output_type -> budget.v1alpha.UpdateFilterResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_budget_v1alpha_filter_service_proto_init() }
func file_budget_v1alpha_filter_service_proto_init() {
	if File_budget_v1alpha_filter_service_proto != nil {
		return
	}
	file_budget_v1alpha_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_budget_v1alpha_filter_service_proto_rawDesc), len(file_budget_v1alpha_filter_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_budget_v1alpha_filter_service_proto_goTypes,
		DependencyIndexes: file_budget_v1alpha_filter_service_proto_depIdxs,
		EnumInfos:         file_budget_v1alpha_filter_service_proto_enumTypes,
		MessageInfos:      file_budget_v1alpha_filter_service_proto_msgTypes,
	}.Build()
	File_budget_v1alpha_filter_service_proto = out.File
	file_budget_v1alpha_filter_service_proto_goTypes = nil
	file_budget_v1alpha_filter_service_proto_depIdxs = nil
}
