// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: budget/v1alpha/timeframe_service.proto

package budgetv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Code represents the status code of a given timeframe.
type TimeframeStatusResponse_Code int32

const (
	TimeframeStatusResponse_CODE_UNSPECIFIED TimeframeStatusResponse_Code = 0
	// CODE_OK means user is allow to select the given timeframe.
	TimeframeStatusResponse_CODE_OK TimeframeStatusResponse_Code = 1
	// CODE_NO_DATA means connection is not set, so no data to show.
	TimeframeStatusResponse_CODE_NO_DATA TimeframeStatusResponse_Code = 2
	// CODE_NOT_ENOUGH means there are not enough data to show for the given timeframe.
	TimeframeStatusResponse_CODE_NOT_ENOUGH TimeframeStatusResponse_Code = 3
)

// Enum value maps for TimeframeStatusResponse_Code.
var (
	TimeframeStatusResponse_Code_name = map[int32]string{
		0: "CODE_UNSPECIFIED",
		1: "CODE_OK",
		2: "CODE_NO_DATA",
		3: "CODE_NOT_ENOUGH",
	}
	TimeframeStatusResponse_Code_value = map[string]int32{
		"CODE_UNSPECIFIED": 0,
		"CODE_OK":          1,
		"CODE_NO_DATA":     2,
		"CODE_NOT_ENOUGH":  3,
	}
)

func (x TimeframeStatusResponse_Code) Enum() *TimeframeStatusResponse_Code {
	p := new(TimeframeStatusResponse_Code)
	*p = x
	return p
}

func (x TimeframeStatusResponse_Code) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimeframeStatusResponse_Code) Descriptor() protoreflect.EnumDescriptor {
	return file_budget_v1alpha_timeframe_service_proto_enumTypes[0].Descriptor()
}

func (TimeframeStatusResponse_Code) Type() protoreflect.EnumType {
	return &file_budget_v1alpha_timeframe_service_proto_enumTypes[0]
}

func (x TimeframeStatusResponse_Code) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimeframeStatusResponse_Code.Descriptor instead.
func (TimeframeStatusResponse_Code) EnumDescriptor() ([]byte, []int) {
	return file_budget_v1alpha_timeframe_service_proto_rawDescGZIP(), []int{1, 0}
}

type TimeframeStatusRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// connection_name is the name of this connection and its resources in argo/k8s
	ConnectionName string `protobuf:"bytes,1,opt,name=connection_name,json=connectionName,proto3" json:"connection_name,omitempty"`
	// namespace is the kubernetes namespace to install into.
	Namespace     string `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeframeStatusRequest) Reset() {
	*x = TimeframeStatusRequest{}
	mi := &file_budget_v1alpha_timeframe_service_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeframeStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeframeStatusRequest) ProtoMessage() {}

func (x *TimeframeStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_timeframe_service_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeframeStatusRequest.ProtoReflect.Descriptor instead.
func (*TimeframeStatusRequest) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_timeframe_service_proto_rawDescGZIP(), []int{0}
}

func (x *TimeframeStatusRequest) GetConnectionName() string {
	if x != nil {
		return x.ConnectionName
	}
	return ""
}

func (x *TimeframeStatusRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

type TimeframeStatusResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// statuses contains status of each timeframe.
	// Note: this array will not contain duplicate timeframes.
	Statuses []*TimeframeStatusResponse_Status `protobuf:"bytes,1,rep,name=statuses,proto3" json:"statuses,omitempty"`
	// trace will contain true if there are data for traces.
	// Otherwise, this will contain false.
	// Note: this containing true just means there are data,
	// and it doesn't necessarily mean there will be data
	// for the user's selected timeframe.
	Trace bool `protobuf:"varint,2,opt,name=trace,proto3" json:"trace,omitempty"`
	// log will contain true if there are data for logs.
	// Otherwise, this will contain false.
	// Note: this containing true just means there are data,
	// and it doesn't necessarily mean there will be data
	// for the user's selected timeframe.
	Log           bool `protobuf:"varint,3,opt,name=log,proto3" json:"log,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeframeStatusResponse) Reset() {
	*x = TimeframeStatusResponse{}
	mi := &file_budget_v1alpha_timeframe_service_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeframeStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeframeStatusResponse) ProtoMessage() {}

func (x *TimeframeStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_timeframe_service_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeframeStatusResponse.ProtoReflect.Descriptor instead.
func (*TimeframeStatusResponse) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_timeframe_service_proto_rawDescGZIP(), []int{1}
}

func (x *TimeframeStatusResponse) GetStatuses() []*TimeframeStatusResponse_Status {
	if x != nil {
		return x.Statuses
	}
	return nil
}

func (x *TimeframeStatusResponse) GetTrace() bool {
	if x != nil {
		return x.Trace
	}
	return false
}

func (x *TimeframeStatusResponse) GetLog() bool {
	if x != nil {
		return x.Log
	}
	return false
}

type TimeframeStatusResponse_Status struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// timeframe contains the timeframe.
	Timeframe Timeframe `protobuf:"varint,1,opt,name=timeframe,proto3,enum=budget.v1alpha.Timeframe" json:"timeframe,omitempty"`
	// status contains the status code of the timeframe.
	Status        TimeframeStatusResponse_Code `protobuf:"varint,3,opt,name=status,proto3,enum=budget.v1alpha.TimeframeStatusResponse_Code" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TimeframeStatusResponse_Status) Reset() {
	*x = TimeframeStatusResponse_Status{}
	mi := &file_budget_v1alpha_timeframe_service_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TimeframeStatusResponse_Status) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TimeframeStatusResponse_Status) ProtoMessage() {}

func (x *TimeframeStatusResponse_Status) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_timeframe_service_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TimeframeStatusResponse_Status.ProtoReflect.Descriptor instead.
func (*TimeframeStatusResponse_Status) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_timeframe_service_proto_rawDescGZIP(), []int{1, 0}
}

func (x *TimeframeStatusResponse_Status) GetTimeframe() Timeframe {
	if x != nil {
		return x.Timeframe
	}
	return Timeframe_TIMEFRAME_UNSPECIFIED
}

func (x *TimeframeStatusResponse_Status) GetStatus() TimeframeStatusResponse_Code {
	if x != nil {
		return x.Status
	}
	return TimeframeStatusResponse_CODE_UNSPECIFIED
}

var File_budget_v1alpha_timeframe_service_proto protoreflect.FileDescriptor

const file_budget_v1alpha_timeframe_service_proto_rawDesc = "" +
	"\n" +
	"&budget/v1alpha/timeframe_service.proto\x12\x0ebudget.v1alpha\x1a\x19budget/v1alpha/type.proto\x1a\x1bbuf/validate/validate.proto\"\xb8\x01\n" +
	"\x16TimeframeStatusRequest\x12S\n" +
	"\x0fconnection_name\x18\x01 \x01(\tB*\xbaH'r%\x10\x03\x18\x142\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\x0econnectionName\x12I\n" +
	"\tnamespace\x18\x02 \x01(\tB+\xbaH(\xc8\x01\x01r#\x18?2\x1f^[a-z0-9]([-a-z0-9]*[a-z0-9])?$R\tnamespace\"\xe9\x02\n" +
	"\x17TimeframeStatusResponse\x12J\n" +
	"\bstatuses\x18\x01 \x03(\v2..budget.v1alpha.TimeframeStatusResponse.StatusR\bstatuses\x12\x14\n" +
	"\x05trace\x18\x02 \x01(\bR\x05trace\x12\x10\n" +
	"\x03log\x18\x03 \x01(\bR\x03log\x1a\x87\x01\n" +
	"\x06Status\x127\n" +
	"\ttimeframe\x18\x01 \x01(\x0e2\x19.budget.v1alpha.TimeframeR\ttimeframe\x12D\n" +
	"\x06status\x18\x03 \x01(\x0e2,.budget.v1alpha.TimeframeStatusResponse.CodeR\x06status\"P\n" +
	"\x04Code\x12\x14\n" +
	"\x10CODE_UNSPECIFIED\x10\x00\x12\v\n" +
	"\aCODE_OK\x10\x01\x12\x10\n" +
	"\fCODE_NO_DATA\x10\x02\x12\x13\n" +
	"\x0fCODE_NOT_ENOUGH\x10\x032{\n" +
	"\x10TimeframeService\x12g\n" +
	"\x0fTimeframeStatus\x12&.budget.v1alpha.TimeframeStatusRequest\x1a'.budget.v1alpha.TimeframeStatusResponse\"\x03\x90\x02\x01B\xd0\x01\n" +
	"\x12com.budget.v1alphaB\x15TimeframeServiceProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha;budgetv1alpha\xa2\x02\x03BXX\xaa\x02\x0eBudget.V1alpha\xca\x02\x0eBudget\\V1alpha\xe2\x02\x1aBudget\\V1alpha\\GPBMetadata\xea\x02\x0fBudget::V1alphab\x06proto3"

var (
	file_budget_v1alpha_timeframe_service_proto_rawDescOnce sync.Once
	file_budget_v1alpha_timeframe_service_proto_rawDescData []byte
)

func file_budget_v1alpha_timeframe_service_proto_rawDescGZIP() []byte {
	file_budget_v1alpha_timeframe_service_proto_rawDescOnce.Do(func() {
		file_budget_v1alpha_timeframe_service_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_budget_v1alpha_timeframe_service_proto_rawDesc), len(file_budget_v1alpha_timeframe_service_proto_rawDesc)))
	})
	return file_budget_v1alpha_timeframe_service_proto_rawDescData
}

var file_budget_v1alpha_timeframe_service_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_budget_v1alpha_timeframe_service_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_budget_v1alpha_timeframe_service_proto_goTypes = []any{
	(TimeframeStatusResponse_Code)(0),      // 0: budget.v1alpha.TimeframeStatusResponse.Code
	(*TimeframeStatusRequest)(nil),         // 1: budget.v1alpha.TimeframeStatusRequest
	(*TimeframeStatusResponse)(nil),        // 2: budget.v1alpha.TimeframeStatusResponse
	(*TimeframeStatusResponse_Status)(nil), // 3: budget.v1alpha.TimeframeStatusResponse.Status
	(Timeframe)(0),                         // 4: budget.v1alpha.Timeframe
}
var file_budget_v1alpha_timeframe_service_proto_depIdxs = []int32{
	3, // 0: budget.v1alpha.TimeframeStatusResponse.statuses:type_name -> budget.v1alpha.TimeframeStatusResponse.Status
	4, // 1: budget.v1alpha.TimeframeStatusResponse.Status.timeframe:type_name -> budget.v1alpha.Timeframe
	0, // 2: budget.v1alpha.TimeframeStatusResponse.Status.status:type_name -> budget.v1alpha.TimeframeStatusResponse.Code
	1, // 3: budget.v1alpha.TimeframeService.TimeframeStatus:input_type -> budget.v1alpha.TimeframeStatusRequest
	2, // 4: budget.v1alpha.TimeframeService.TimeframeStatus:output_type -> budget.v1alpha.TimeframeStatusResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_budget_v1alpha_timeframe_service_proto_init() }
func file_budget_v1alpha_timeframe_service_proto_init() {
	if File_budget_v1alpha_timeframe_service_proto != nil {
		return
	}
	file_budget_v1alpha_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_budget_v1alpha_timeframe_service_proto_rawDesc), len(file_budget_v1alpha_timeframe_service_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_budget_v1alpha_timeframe_service_proto_goTypes,
		DependencyIndexes: file_budget_v1alpha_timeframe_service_proto_depIdxs,
		EnumInfos:         file_budget_v1alpha_timeframe_service_proto_enumTypes,
		MessageInfos:      file_budget_v1alpha_timeframe_service_proto_msgTypes,
	}.Build()
	File_budget_v1alpha_timeframe_service_proto = out.File
	file_budget_v1alpha_timeframe_service_proto_goTypes = nil
	file_budget_v1alpha_timeframe_service_proto_depIdxs = nil
}
