// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: budget/v1alpha/type.proto

package budgetv1alpha

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Timeframe represents possible timeframes.
type Timeframe int32

const (
	Timeframe_TIMEFRAME_UNSPECIFIED Timeframe = 0
	// TIMEFRAME_24HR means the last 24 hours.
	Timeframe_TIMEFRAME_24HR Timeframe = 1
	// TIMEFRAME_MTD means month to date.
	Timeframe_TIMEFRAME_MTD Timeframe = 2
	// TIMEFRAME_LM means last month.
	Timeframe_TIMEFRAME_LM Timeframe = 3
)

// Enum value maps for Timeframe.
var (
	Timeframe_name = map[int32]string{
		0: "TIMEFRAME_UNSPECIFIED",
		1: "TIMEFRAME_24HR",
		2: "TIMEFRAME_MTD",
		3: "TIMEFRAME_LM",
	}
	Timeframe_value = map[string]int32{
		"TIMEFRAME_UNSPECIFIED": 0,
		"TIMEFRAME_24HR":        1,
		"TIMEFRAME_MTD":         2,
		"TIMEFRAME_LM":          3,
	}
)

func (x Timeframe) Enum() *Timeframe {
	p := new(Timeframe)
	*p = x
	return p
}

func (x Timeframe) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Timeframe) Descriptor() protoreflect.EnumDescriptor {
	return file_budget_v1alpha_type_proto_enumTypes[0].Descriptor()
}

func (Timeframe) Type() protoreflect.EnumType {
	return &file_budget_v1alpha_type_proto_enumTypes[0]
}

func (x Timeframe) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Timeframe.Descriptor instead.
func (Timeframe) EnumDescriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{0}
}

// FilterType represents the type of filters supported.
type FilterType int32

const (
	FilterType_FILTER_TYPE_UNSPECIFIED FilterType = 0
	FilterType_FILTER_TYPE_LOG         FilterType = 1
	FilterType_FILTER_TYPE_TRACE       FilterType = 2
)

// Enum value maps for FilterType.
var (
	FilterType_name = map[int32]string{
		0: "FILTER_TYPE_UNSPECIFIED",
		1: "FILTER_TYPE_LOG",
		2: "FILTER_TYPE_TRACE",
	}
	FilterType_value = map[string]int32{
		"FILTER_TYPE_UNSPECIFIED": 0,
		"FILTER_TYPE_LOG":         1,
		"FILTER_TYPE_TRACE":       2,
	}
)

func (x FilterType) Enum() *FilterType {
	p := new(FilterType)
	*p = x
	return p
}

func (x FilterType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FilterType) Descriptor() protoreflect.EnumDescriptor {
	return file_budget_v1alpha_type_proto_enumTypes[1].Descriptor()
}

func (FilterType) Type() protoreflect.EnumType {
	return &file_budget_v1alpha_type_proto_enumTypes[1]
}

func (x FilterType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FilterType.Descriptor instead.
func (FilterType) EnumDescriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{1}
}

type Filter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// type contains the filter type.
	Type FilterType `protobuf:"varint,1,opt,name=type,proto3,enum=budget.v1alpha.FilterType" json:"type,omitempty"`
	// pct_sampled contains the sampling percentage.
	PctSampled uint32 `protobuf:"varint,2,opt,name=pct_sampled,json=pctSampled,proto3" json:"pct_sampled,omitempty"`
	// include_err indcates if errors should be included.
	IncludeErr    bool `protobuf:"varint,3,opt,name=include_err,json=includeErr,proto3" json:"include_err,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Filter) Reset() {
	*x = Filter{}
	mi := &file_budget_v1alpha_type_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Filter) ProtoMessage() {}

func (x *Filter) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_type_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Filter.ProtoReflect.Descriptor instead.
func (*Filter) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{0}
}

func (x *Filter) GetType() FilterType {
	if x != nil {
		return x.Type
	}
	return FilterType_FILTER_TYPE_UNSPECIFIED
}

func (x *Filter) GetPctSampled() uint32 {
	if x != nil {
		return x.PctSampled
	}
	return 0
}

func (x *Filter) GetIncludeErr() bool {
	if x != nil {
		return x.IncludeErr
	}
	return false
}

type Overall struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// cost contains the total cost for log and trace, rounding to the nearest two decimal places.
	Cost float64 `protobuf:"fixed64,1,opt,name=cost,proto3" json:"cost,omitempty"`
	// saving_pct is the total cost saving percentage for log and trace, rounding to the nearest two decimal places (e.g., 1.23%).
	SavingPct float32 `protobuf:"fixed32,2,opt,name=saving_pct,json=savingPct,proto3" json:"saving_pct,omitempty"`
	// log contains overall metric data for logs.
	Log *Overall_Metric `protobuf:"bytes,3,opt,name=log,proto3" json:"log,omitempty"`
	// trace contains overall metric data for traces.
	Trace         *Overall_Metric `protobuf:"bytes,4,opt,name=trace,proto3" json:"trace,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overall) Reset() {
	*x = Overall{}
	mi := &file_budget_v1alpha_type_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overall) ProtoMessage() {}

func (x *Overall) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_type_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overall.ProtoReflect.Descriptor instead.
func (*Overall) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{1}
}

func (x *Overall) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Overall) GetSavingPct() float32 {
	if x != nil {
		return x.SavingPct
	}
	return 0
}

func (x *Overall) GetLog() *Overall_Metric {
	if x != nil {
		return x.Log
	}
	return nil
}

func (x *Overall) GetTrace() *Overall_Metric {
	if x != nil {
		return x.Trace
	}
	return nil
}

type Log struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the service name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// received represents the amount of data recieved (in GB).
	Received uint64 `protobuf:"varint,2,opt,name=received,proto3" json:"received,omitempty"`
	// received represents the amount of data send (in GB).
	Sent uint64 `protobuf:"varint,3,opt,name=sent,proto3" json:"sent,omitempty"`
	// pct contains the percentage of total log cost, rounding to the nearest two decimal places (e.g., 1.23%).
	Pct float32 `protobuf:"fixed32,4,opt,name=pct,proto3" json:"pct,omitempty"`
	// cost contains the total cost, rounding to the nearest two decimal places.
	Cost          float64 `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_budget_v1alpha_type_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_type_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{2}
}

func (x *Log) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Log) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *Log) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Log) GetPct() float32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *Log) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type Span struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// name is the trace root span name.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// breath contains the span breath.
	Breath uint32 `protobuf:"varint,2,opt,name=breath,proto3" json:"breath,omitempty"`
	// depth contains the span depth.
	Depth uint32 `protobuf:"varint,3,opt,name=depth,proto3" json:"depth,omitempty"`
	// invocations contains the number of invocations.
	Invocations uint32 `protobuf:"varint,4,opt,name=invocations,proto3" json:"invocations,omitempty"`
	// received represents the amount of data recieved (in mm Events).
	Received uint64 `protobuf:"varint,5,opt,name=received,proto3" json:"received,omitempty"`
	// received represents the amount of data send (in mm Events).
	Sent uint64 `protobuf:"varint,6,opt,name=sent,proto3" json:"sent,omitempty"`
	// pct contains the percentage of total trace cost, rounding to the nearest two decimal places (e.g., 1.23%).
	Pct float32 `protobuf:"fixed32,7,opt,name=pct,proto3" json:"pct,omitempty"`
	// cost contains the total cost, rounding to the nearest two decimal places.
	Cost          float64 `protobuf:"fixed64,8,opt,name=cost,proto3" json:"cost,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Span) Reset() {
	*x = Span{}
	mi := &file_budget_v1alpha_type_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Span) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Span) ProtoMessage() {}

func (x *Span) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_type_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Span.ProtoReflect.Descriptor instead.
func (*Span) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{3}
}

func (x *Span) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Span) GetBreath() uint32 {
	if x != nil {
		return x.Breath
	}
	return 0
}

func (x *Span) GetDepth() uint32 {
	if x != nil {
		return x.Depth
	}
	return 0
}

func (x *Span) GetInvocations() uint32 {
	if x != nil {
		return x.Invocations
	}
	return 0
}

func (x *Span) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *Span) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Span) GetPct() float32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *Span) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

type Overall_Metric struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// received represents the total amount of data recieved.
	// For log, the unit is in GB; For trace, the unit is in mm Events.
	Received uint64 `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	// sent represents the total amount of data send.
	// For log, the unit is in GB; For trace, the unit is in mm Events.
	Sent uint64 `protobuf:"varint,2,opt,name=sent,proto3" json:"sent,omitempty"`
	// cost_rate contains the per GB (for log) or the per mm Events (for traces) cost rate, rounding to the nearest two decimal places.
	CostRate float32 `protobuf:"fixed32,3,opt,name=cost_rate,json=costRate,proto3" json:"cost_rate,omitempty"`
	// pct contains the percentage of total overall cost, rounding to the nearest two decimal places (e.g., 1.23%).
	Pct float32 `protobuf:"fixed32,4,opt,name=pct,proto3" json:"pct,omitempty"`
	// cost contains the total cost, rounding to the nearest two decimal places.
	Cost float64 `protobuf:"fixed64,5,opt,name=cost,proto3" json:"cost,omitempty"`
	// reduction_pct contains the percentage of data volumn reduced, rounding to the nearest two decimal places (e.g., 1.23%).
	ReductionPct  float32 `protobuf:"fixed32,6,opt,name=reduction_pct,json=reductionPct,proto3" json:"reduction_pct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Overall_Metric) Reset() {
	*x = Overall_Metric{}
	mi := &file_budget_v1alpha_type_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Overall_Metric) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Overall_Metric) ProtoMessage() {}

func (x *Overall_Metric) ProtoReflect() protoreflect.Message {
	mi := &file_budget_v1alpha_type_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Overall_Metric.ProtoReflect.Descriptor instead.
func (*Overall_Metric) Descriptor() ([]byte, []int) {
	return file_budget_v1alpha_type_proto_rawDescGZIP(), []int{1, 0}
}

func (x *Overall_Metric) GetReceived() uint64 {
	if x != nil {
		return x.Received
	}
	return 0
}

func (x *Overall_Metric) GetSent() uint64 {
	if x != nil {
		return x.Sent
	}
	return 0
}

func (x *Overall_Metric) GetCostRate() float32 {
	if x != nil {
		return x.CostRate
	}
	return 0
}

func (x *Overall_Metric) GetPct() float32 {
	if x != nil {
		return x.Pct
	}
	return 0
}

func (x *Overall_Metric) GetCost() float64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *Overall_Metric) GetReductionPct() float32 {
	if x != nil {
		return x.ReductionPct
	}
	return 0
}

var File_budget_v1alpha_type_proto protoreflect.FileDescriptor

const file_budget_v1alpha_type_proto_rawDesc = "" +
	"\n" +
	"\x19budget/v1alpha/type.proto\x12\x0ebudget.v1alpha\x1a\x1bbuf/validate/validate.proto\"\x95\x01\n" +
	"\x06Filter\x12;\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1a.budget.v1alpha.FilterTypeB\v\xbaH\b\xc8\x01\x01\x82\x01\x02\x10\x01R\x04type\x12-\n" +
	"\vpct_sampled\x18\x02 \x01(\rB\f\xbaH\t\xc8\x01\x01*\x04\x10e(\x00R\n" +
	"pctSampled\x12\x1f\n" +
	"\vinclude_err\x18\x03 \x01(\bR\n" +
	"includeErr\"\xc7\x02\n" +
	"\aOverall\x12\x12\n" +
	"\x04cost\x18\x01 \x01(\x01R\x04cost\x12\x1d\n" +
	"\n" +
	"saving_pct\x18\x02 \x01(\x02R\tsavingPct\x120\n" +
	"\x03log\x18\x03 \x01(\v2\x1e.budget.v1alpha.Overall.MetricR\x03log\x124\n" +
	"\x05trace\x18\x04 \x01(\v2\x1e.budget.v1alpha.Overall.MetricR\x05trace\x1a\xa0\x01\n" +
	"\x06Metric\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\x04R\breceived\x12\x12\n" +
	"\x04sent\x18\x02 \x01(\x04R\x04sent\x12\x1b\n" +
	"\tcost_rate\x18\x03 \x01(\x02R\bcostRate\x12\x10\n" +
	"\x03pct\x18\x04 \x01(\x02R\x03pct\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\x12#\n" +
	"\rreduction_pct\x18\x06 \x01(\x02R\freductionPct\"o\n" +
	"\x03Log\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\breceived\x18\x02 \x01(\x04R\breceived\x12\x12\n" +
	"\x04sent\x18\x03 \x01(\x04R\x04sent\x12\x10\n" +
	"\x03pct\x18\x04 \x01(\x02R\x03pct\x12\x12\n" +
	"\x04cost\x18\x05 \x01(\x01R\x04cost\"\xc0\x01\n" +
	"\x04Span\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x16\n" +
	"\x06breath\x18\x02 \x01(\rR\x06breath\x12\x14\n" +
	"\x05depth\x18\x03 \x01(\rR\x05depth\x12 \n" +
	"\vinvocations\x18\x04 \x01(\rR\vinvocations\x12\x1a\n" +
	"\breceived\x18\x05 \x01(\x04R\breceived\x12\x12\n" +
	"\x04sent\x18\x06 \x01(\x04R\x04sent\x12\x10\n" +
	"\x03pct\x18\a \x01(\x02R\x03pct\x12\x12\n" +
	"\x04cost\x18\b \x01(\x01R\x04cost*_\n" +
	"\tTimeframe\x12\x19\n" +
	"\x15TIMEFRAME_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eTIMEFRAME_24HR\x10\x01\x12\x11\n" +
	"\rTIMEFRAME_MTD\x10\x02\x12\x10\n" +
	"\fTIMEFRAME_LM\x10\x03*U\n" +
	"\n" +
	"FilterType\x12\x1b\n" +
	"\x17FILTER_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFILTER_TYPE_LOG\x10\x01\x12\x15\n" +
	"\x11FILTER_TYPE_TRACE\x10\x02B\xc4\x01\n" +
	"\x12com.budget.v1alphaB\tTypeProtoP\x01ZJgithub.com/MyDecisive/octant-contracts/go/pkg/budget/v1alpha;budgetv1alpha\xa2\x02\x03BXX\xaa\x02\x0eBudget.V1alpha\xca\x02\x0eBudget\\V1alpha\xe2\x02\x1aBudget\\V1alpha\\GPBMetadata\xea\x02\x0fBudget::V1alphab\x06proto3"

var (
	file_budget_v1alpha_type_proto_rawDescOnce sync.Once
	file_budget_v1alpha_type_proto_rawDescData []byte
)

func file_budget_v1alpha_type_proto_rawDescGZIP() []byte {
	file_budget_v1alpha_type_proto_rawDescOnce.Do(func() {
		file_budget_v1alpha_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_budget_v1alpha_type_proto_rawDesc), len(file_budget_v1alpha_type_proto_rawDesc)))
	})
	return file_budget_v1alpha_type_proto_rawDescData
}

var file_budget_v1alpha_type_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_budget_v1alpha_type_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_budget_v1alpha_type_proto_goTypes = []any{
	(Timeframe)(0),         // 0: budget.v1alpha.Timeframe
	(FilterType)(0),        // 1: budget.v1alpha.FilterType
	(*Filter)(nil),         // 2: budget.v1alpha.Filter
	(*Overall)(nil),        // 3: budget.v1alpha.Overall
	(*Log)(nil),            // 4: budget.v1alpha.Log
	(*Span)(nil),           // 5: budget.v1alpha.Span
	(*Overall_Metric)(nil), // 6: budget.v1alpha.Overall.Metric
}
var file_budget_v1alpha_type_proto_depIdxs = []int32{
	1, // 0: budget.v1alpha.Filter.type:type_name -> budget.v1alpha.FilterType
	6, // 1: budget.v1alpha.Overall.log:type_name -> budget.v1alpha.Overall.Metric
	6, // 2: budget.v1alpha.Overall.trace:type_name -> budget.v1alpha.Overall.Metric
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_budget_v1alpha_type_proto_init() }
func file_budget_v1alpha_type_proto_init() {
	if File_budget_v1alpha_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_budget_v1alpha_type_proto_rawDesc), len(file_budget_v1alpha_type_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_budget_v1alpha_type_proto_goTypes,
		DependencyIndexes: file_budget_v1alpha_type_proto_depIdxs,
		EnumInfos:         file_budget_v1alpha_type_proto_enumTypes,
		MessageInfos:      file_budget_v1alpha_type_proto_msgTypes,
	}.Build()
	File_budget_v1alpha_type_proto = out.File
	file_budget_v1alpha_type_proto_goTypes = nil
	file_budget_v1alpha_type_proto_depIdxs = nil
}
