syntax = "proto3";

package octant.v1alpha;

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";
import "octant/v1alpha/type.proto";

// ConnectService allows for interacting with MDAI Octant Connections
service ConnectionService {
  // GetConnections gets all existing connection names
  rpc GetConnections(google.protobuf.Empty) returns (GetConnectionsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  // GetConnection gets details about a connection
  rpc GetConnection(GetConnectionRequest) returns (GetConnectionResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  // CreateConnection creates a connection and deploys it
  rpc CreateConnection(CreateConnectionRequest) returns (google.protobuf.Empty) {}
  // DeleteConnection removes an existing connection and its associated resources
  rpc DeleteConnection(DeleteConnectionRequest) returns (google.protobuf.Empty) {}
  // GetConnectionValidatorRuns gets the validator runs that exist in the validation dataset
  rpc GetConnectionValidatorRunIds(GetConnectionValidatorRunIdsRequest) returns (GetConnectionValidatorRunIdsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  // CreateConnectionValidatorRun creates a new validator run for the given connection. Will create a new validator run if one already exists.
  rpc CreateConnectionValidatorRun(CreateConnectionValidatorRunRequest) returns (CreateConnectionValidatorRunResponse) {}
  // DeleteConnectionValidator deletes connection validator resources
  rpc DeleteConnectionValidator(DeleteConnectionValidatorRequest) returns (google.protobuf.Empty) {}
  // GetConnectionStatus gets the status of a connection based on dataflow and validation metrics
  rpc GetConnectionStatus(GetConnectionStatusRequest) returns (GetConnectionStatusResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  // GenerateManifests generates the manifest base on the given input and this will returns
  // the compressed zip file containing the manifests as a stream of raw bytes.
  // Note: To create a download link in the FE, the stream of file content data should be stored
  // in a typed blob and then https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static
  // should be used.
  rpc GenerateManifests(GenerateManifestsRequest) returns (stream GenerateManifestsResponse) {}
}

// ConnectionScope contains identifiers for a connection
message ConnectionScope {
  // namespace that the connection is installed in/will be installed into
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of the connection
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

// GetConnectionResponse has details on a connection
message GetConnectionResponse {
  // telemetry_types are the MLT telemetry types for this connection
  repeated MLTType telemetry_types = 1;
  // deployment_type is the deployment mechanism
  DeploymentType deployment_type = 2;
  // destinations are where telemetry for this connection flows to
  repeated TelemetryDestination destinations = 3;
}

// GetConnectionRequest are fields required to fetch a connection
message GetConnectionRequest {
  // connection_name is the name of the connection
  string connection_name = 1 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

// GetConnectionsResponse contains a list of all the connections in a namespace
message GetConnectionsResponse {
  // connection_names are the connection names found in the namespace
  repeated string connection_names = 1;
}

// CreateConnectionRequest contains options for creating a connection
message CreateConnectionRequest {
  ConnectionScope scope = 1 [(buf.validate.field).required = true];
  // telemetry_types is used to generate the manifests.
  repeated MLTType telemetry_types = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      enum: {defined_only: true}
    }
  ];
  // deployment contains information required for deploying the connection
  Deployment deployment = 3 [(buf.validate.field).required = true];
  // destinations are where telemetry from this connection is sent and options needed to send it there
  repeated TelemetryDestination destinations = 4 [(buf.validate.field).required = true];
}

// TelemetryDestination is information for an integration to send telemetry to from a connection
message TelemetryDestination {
  // type is the integration type for this integration
  IntegrationType type = 1;
  // integration_name is the name of a previously created integration with information needed to send telemetry
  string integration_name = 2;
}

// Deployment is information needed to deploy a connection
message Deployment {
  // type indicates what type of deployment mechanism/system to use
  DeploymentType type = 1;
  // integration_name is the name of the previously created deployment integration to use
  string integration_name = 2;
}

// IntegrationType is the type of integration for destinations or deployments
enum IntegrationType {
  // INTEGRATION_TYPE_UNSPECIFIED is unsupported and should not be used
  INTEGRATION_TYPE_UNSPECIFIED = 0;
  // INTEGRATION_TYPE_DATADOG is for datadog telemetry destinations
  INTEGRATION_TYPE_DATADOG = 1;
}

message GenerateManifestsRequest {
  ConnectionScope scope = 1 [(buf.validate.field).required = true];
  // format contains output format of the manifests.
  ManifestOutFormat format = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  // deployment_type use to tell the type of manifest to generate.
  DeploymentType deployment_type = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  // telemetry_types is used to generate the manifests.
  repeated MLTType telemetry_types = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      enum: {defined_only: true}
    }
  ];
  // mdai_version is the mdai hub version to use for app install.
  string mdai_version = 5 [(buf.validate.field).string.pattern = "^(\\d+\\.\\d+\\.\\d+(-[a-z]*)?)|latest$"];
}

message GenerateManifestsResponse {
  // data contains a chunk of the file content as raw bytes.
  bytes data = 1;
  // total is the total number of bytes for current file.
  uint64 total = 2;
  // type is the MIME type of the file. (e.g., zip)
  string type = 3;
}

// GetConnectionValidatorRunIdsRequest is a request to get all available connection validator runs
message GetConnectionValidatorRunIdsRequest {
  ConnectionScope scope = 1 [(buf.validate.field).required = true];
}

// GetConnectionValidatorRunIdsResponse provides all the validator run ids for a connection
message GetConnectionValidatorRunIdsResponse {
  // validator_run_ids is the list of validator_run_ids currently available in the metrics set
  repeated string validator_run_ids = 1;
}

// CreateConnectionValidatorRunRequest has options for creating a connection validator
message CreateConnectionValidatorRunRequest {
  ConnectionScope scope = 1 [(buf.validate.field).required = true];
}

// CreateConnectionValidatorRunResponse contains a response for validator creation
message CreateConnectionValidatorRunResponse {
  // validator_run_id is the created validator_run_id for the new validator run
  string validator_run_id = 1;
}

// DeleteConnectionValidatorRequest contains options for deleting a connection validator
message DeleteConnectionValidatorRequest {
  ConnectionScope scope = 1 [(buf.validate.field).required = true];
}

// GetConnectionStatusRequest contains options for getting a connections validator run results
message GetConnectionStatusRequest {
  ConnectionScope scope = 1 [(buf.validate.field).required = true];
  // validator_run_id is the Validator Run ID to get validation metrics for. Omitting this will yield empty/false validation results in the response.
  string validator_run_id = 2;
}

message GetConnectionStatusResponse {
  // receiving_data indicates if the Connection's Collector is receiving telemetry for its configured Telemetry types
  bool receiving_data = 1 [(buf.validate.field).required = true];
  // sending_data indicates if the Connection's Collector is sending telemetry for its configured Telemetry types
  bool sending_data = 2 [(buf.validate.field).required = true];
  // sending_data indicates if the data coming to the Collector fulfills validator parity or policy requirements
  bool data_integrity = 3 [(buf.validate.field).required = true];
  // clients_connected indicates if the Connection's Collector is connected for its configured Telemetry types
  bool clients_connected = 4 [(buf.validate.field).required = true];
  // validation_results is a map of granular validation details per data type (MLT)
  ValidationResultsBySignal validation_results = 5;
}

message ValidationResultsBySignal {
  ValidationResult logs = 1;
  ValidationResult metrics = 2;
  ValidationResult traces = 3;
}

message ValidationResult {
  // parity indicates if the ingress telemetry payloads match the egress telemetry payloads
  bool parity = 1;
  // parity indicates if the egress telemetry payloads fulfill the MDAI validator policy
  bool policy = 2;
  // attributes is a map of attributes to per-attribute parity/policy checks
  ValidationAttributes attributes = 3;
}

message ValidationAttributes {
  // parity indicates if the ingress attribute matches the attribute on egress
  map<string, bool> parity = 1;
  // parity indicates if the attribute fulfills the MDAI validator policy for this attribute
  map<string, bool> policy = 2;
}

message DeleteConnectionRequest {
  // connection_name is the name of the connection to delete
  string connection_name = 1 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}
