syntax = "proto3";

package octant.v1alpha;

import "buf/validate/validate.proto";
import "octant/v1alpha/type.proto";

// ConnectService allows for interacting with MDAI Octant Connections
service ConnectionService {
  rpc GetConnections(GetConnectionsRequest) returns (GetConnectionsResponse) {}
  rpc GetConnection(GetConnectionRequest) returns (GetConnectionResponse) {}
  rpc PutConnection(PutConnectionRequest) returns (PutConnectionResponse) {}
  // GetConnectionValidatorRuns gets the validator runs that exist in the validation dataset
  rpc GetConnectionValidatorRuns(GetConnectionValidatorRunsRequest) returns (GetConnectionValidatorRunsResponse) {}
  // PutConnectionValidatorRun creates a new validator run for the given connection. Will create a new validator run if one already exists.
  rpc PutConnectionValidatorRun(PutConnectionValidatorRunRequest) returns (PutConnectionValidatorRunResponse) {}
  // GetConnectionStatus gets the status of a connection based on dataflow and validation metrics
  rpc GetConnectionStatus(GetConnectionStatusRequest) returns (GetConnectionStatusResponse) {}
  // GenerateManifests generates the manifest base on the given input and this will returns
  // the compressed zip file containing the manifests as a stream of raw bytes.
  // Note: To create a download link in the FE, the stream of file content data should be stored
  // in a typed blob and then https://developer.mozilla.org/en-US/docs/Web/API/URL/createObjectURL_static
  // should be used.
  rpc GenerateManifests(GenerateManifestsRequest) returns (stream GenerateManifestsResponse) {}
}

message GetConnectionsRequest {
  // namespace is the kubernetes namespace to install into.
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message GetConnectionResponse {
  repeated MLTType telemetry_types = 1;
  DeploymentType deployment_type = 2;

  repeated TelemetryDestination destinations = 3 ;
}

message GetConnectionRequest {
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message GetConnectionsResponse {
  repeated string connection_names = 1;
}

message PutConnectionRequest {
  // namespace is the kubernetes namespace to install into.
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // telemetry_types is used to generate the manifests.
  repeated MLTType telemetry_types = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      enum: {defined_only: true}
    }
  ];
  // deployment_type use to tell the type of manifest to generate.
  DeploymentType deployment_type = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];

  repeated TelemetryDestination destinations = 5 [(buf.validate.field).required = true];
}

message TelemetryDestination {
  IntegrationType type = 1;
  string integration_name = 2;
}

message Deployment {
  DeploymentType type = 1;
  string integration_name = 2;
}

enum IntegrationType {
  INTEGRATION_TYPE_DATADOG = 0;
}

message PutConnectionResponse {
  // validator_run_id is the created validator_run_id for the new validator run
  string validator_run_id = 1;
}

message GenerateManifestsRequest {
  // namespace is the kubernetes namespace to install into.
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // format contains output format of the manifests.
  ManifestOutFormat format = 3 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  // deployment_type use to tell the type of manifest to generate.
  DeploymentType deployment_type = 5 [
    (buf.validate.field).required = true,
    (buf.validate.field).enum.defined_only = true
  ];
  // telemetry_types is used to generate the manifests.
  repeated MLTType telemetry_types = 4 [
    (buf.validate.field).required = true,
    (buf.validate.field).repeated.unique = true,
    (buf.validate.field).repeated.items = {
      enum: {defined_only: true}
    }
  ];
}

message GenerateManifestsResponse {
  // data contains a chunk of the file content as raw bytes.
  bytes data = 1;
  // total is the total number of bytes for current file.
  uint64 total = 2;
  // type is the MIME type of the file. (e.g., zip)
  string type = 3;
}

message GetConnectionValidatorRunsRequest {
  // namespace is the kubernetes namespace to install into.
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message PutConnectionValidatorRunRequest {
  // namespace is the kubernetes namespace to install into.
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
}

message PutConnectionValidatorRunResponse {
  // validator_run_id is the created validator_run_id for the new validator run
  string validator_run_id = 1;
}

message GetConnectionValidatorRunsResponse {
  // validator_run_ids is the list of validator_run_ids currently available in the metrics set
  repeated string validator_run_ids = 1;
}

message GetConnectionStatusRequest {
  // namespace is the kubernetes namespace to install into.
  string namespace = 1 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.max_len = 63,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // connection_name is the name of this connection and its resources in argo/k8s
  string connection_name = 2 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 20,
    (buf.validate.field).string.pattern = "^[a-z0-9]([-a-z0-9]*[a-z0-9])?$"
  ];
  // validator_run_id is the Validator Run ID to get validation metrics for. Omitting this will yield empty/false validation results in the response.
  string validator_run_id = 3;
}

message GetConnectionStatusResponse {
  // receiving_data indicates if the Connection's Collector is receiving telemetry for its configured Telemetry types
  bool receiving_data = 1;
  // sending_data indicates if the Connection's Collector is sending telemetry for its configured Telemetry types
  bool sending_data = 2;
  // sending_data indicates if the data coming to the Collector fulfills validator parity or policy requirements
  bool data_integrity = 3;
  // validation_results is a map of granular validation details per data type (MLT)
  ValidationResultsBySignal validation_results = 4;
}

message ValidationResultsBySignal {
  ValidationResult logs = 1;
  ValidationResult metrics = 2;
  ValidationResult traces = 3;
}

message ValidationResult {
  // parity indicates if the ingress telemetry payloads match the egress telemetry payloads
  bool parity = 1;
  // parity indicates if the egress telemetry payloads fulfill the MDAI validator policy
  bool policy = 2;
  // attributes is a map of attributes to per-attribute parity/policy checks
  ValidationAttributes attributes = 3;
}

message ValidationAttributes {
  // parity indicates if the ingress attribute matches the attribute on egress
  map<string, bool> parity = 1;
  // parity indicates if the attribute fulfills the MDAI validator policy for this attribute
  map<string, bool> policy = 2;
}