syntax = "proto3";

package octant.v1alpha;

import "buf/validate/validate.proto";
import "google/protobuf/empty.proto";

service DatadogService {
  // GetIntegrations returns list of datadog integration names.
  rpc GetDatadogIntegrations(google.protobuf.Empty) returns (GetDatadogIntegrationsResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  // GetDatadogIntegrationByName returns list of datadog integration names.
  rpc GetDatadogIntegrationByName(GetDatadogIntegrationByNameRequest) returns (GetDatadogIntegrationByNameResponse) {
    option idempotency_level = NO_SIDE_EFFECTS;
  }
  // SaveDatadogIntegration saves the given datadog integration.
  // If the integration already exists, this will override the saved data with the one provided.
  rpc SaveDatadogIntegration(SaveDatadogIntegrationRequest) returns (google.protobuf.Empty) {}
}

message GetDatadogIntegrationByNameRequest {
  // name contains name of the integration to retrieve
  string name = 1 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 100
  ];
}

message GetDatadogIntegrationByNameResponse {
  // url is the datadog api url to send telemetry data to.
  string url = 1 [(buf.validate.field).required = true];
}

message GetDatadogIntegrationsResponse {
  // names contains the list of integration names
  repeated string names = 1;
}

message SaveDatadogIntegrationRequest {
  // name contains name of the datadog integration to save
  string name = 1 [
    (buf.validate.field).string.min_len = 3,
    (buf.validate.field).string.max_len = 100
  ];
  // api_key is the 32-character api key generated from datadog.
  string api_key = 2 [
    (buf.validate.field).required = true,
    (buf.validate.field).string.len = 32
  ];
  // site_host is the datadog api domain to send telemetry data to.
  string site_host = 4 [
    (buf.validate.field).cel = {
      id: "SaveDatadogIntegrationRequest.site_host",
      message: "Site host must be a valid hostname, not a URI",
      expression: "this.isHostname()"
    }
  ];
}
